- src/main/java/balancetalk/domain/report/enums/ReportCategory.java
ReportCategory enum에 상업적 광고, 사칭/사기, 욕설/비하, 기타 추가
closes #12
> feat: 신고 카테고리 항목 추가

- src/main/java/balancetalk/domain/Notice.java
- src/main/java/balancetalk/domain/comment/entity/Comment.java
- src/main/java/balancetalk/domain/comment/entity/CommentLike.java
- src/main/java/balancetalk/domain/file/entity/File.java
- src/main/java/balancetalk/domain/file/enums/FileType.java
- src/main/java/balancetalk/domain/member/entity/Member.java
- src/main/java/balancetalk/domain/post/entity/BalanceOption.java
- src/main/java/balancetalk/domain/post/entity/Post.java
- src/main/java/balancetalk/domain/report/entity/Report.java
> feat: entity에 검증 어노테이션 추가

- src/main/java/balancetalk/module/Notice.java
- src/main/java/balancetalk/module/comment/domain/Comment.java
- src/main/java/balancetalk/module/file/domain/File.java
- src/main/java/balancetalk/module/member/domain/Member.java
- src/main/java/balancetalk/module/member/domain/Role.java
- src/main/java/balancetalk/module/post/domain/BalanceOption.java
- src/main/java/balancetalk/module/post/domain/Post.java
- src/main/java/balancetalk/module/post/domain/Tag.java
- src/main/java/balancetalk/module/report/domain/Report.java
각 엔티티 필드의 제약 사항에 맞게 검증 애노테이션을 추가한다.
closes #10
> feat: 검증 애노테이션 추가

- src/main/java/balancetalk/module/post/application/PostService.java
- src/main/java/balancetalk/module/post/presentation/PostController.java
- src/test/java/balancetalk/module/post/application/PostServiceTest.java
> feat: 게시글 전체 조회 기능 추가

- src/main/java/balancetalk/module/post/application/PostService.java
- src/main/java/balancetalk/module/post/presentation/PostController.java
> feat: 게시글 삭제 기능 추가

- src/main/java/balancetalk/module/post/application/BookmarkService.java
- src/main/java/balancetalk/module/post/dto/BookmarkResponseDto.java
- src/main/java/balancetalk/module/post/presentation/BookmarkController.java
- 북마크에 추가된 모든 게시글을 조회하는 기능 구현
- 게시글 북마크 해제 기능 구현
- 북마크 예외 처리 구현
- 단위 테스트 코드 작성
closes #59
> 북마크에 추가된 게시글 전체 목록 조회 기능 구현 완료

- src/main/java/balancetalk/global/exception/ErrorCode.java
- src/main/java/balancetalk/module/post/application/PostService.java
- src/main/java/balancetalk/module/post/domain/Post.java
- src/main/java/balancetalk/module/post/domain/PostLike.java
- src/main/java/balancetalk/module/post/domain/PostLikeRepository.java
- src/main/java/balancetalk/module/post/presentation/PostController.java
- src/test/java/balancetalk/module/post/application/PostServiceTest.java
- src/test/java/balancetalk/module/vote/application/VoteServiceTest.java
> 게시글 추천 기능 구현

- src/main/java/balancetalk/global/exception/ErrorCode.java
- src/main/java/balancetalk/module/comment/application/CommentService.java
- src/main/java/balancetalk/module/comment/domain/CommentLike.java
- src/main/java/balancetalk/module/comment/domain/CommentLikeRepository.java
- src/main/java/balancetalk/module/comment/presentation/CommentController.java
- src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
> 댓글 추천 기능 구현

- src/test/java/balancetalk/module/post/application/BookmarkServiceTest.java
북마크의 모든 기능과 구현한 예외 처리들에 대해서 단위 테스트를 작성하고 통과했습니다.
closes #74
> 북마크 기능, 예외 처리 단위 테스트 구현 및 통과 완료

- src/main/java/balancetalk/global/exception/ErrorCode.java
- src/main/java/balancetalk/module/member/application/MemberService.java
- src/main/java/balancetalk/module/member/dto/MemberResponseDto.java
- src/main/java/balancetalk/module/member/presentation/MemberController.java
- src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
- src/test/java/balancetalk/module/member/application/MemberServiceTest.java
> 멤버 삭제 기능 구현

- src/main/java/balancetalk/module/comment/application/CommentService.java
- src/main/java/balancetalk/module/comment/domain/CommentLikeRepository.java
- src/main/java/balancetalk/module/comment/presentation/CommentController.java
댓글 추천 취소 기능을 구현한다.
closes #67
> 댓글 추천 취소 기능 구현

- src/main/java/balancetalk/module/post/dto/BookmarkRequestDto.java
- src/main/java/balancetalk/module/post/dto/BookmarkResponseDto.java
- src/main/java/balancetalk/module/post/presentation/BookmarkController.java
- src/main/java/balancetalk/module/vote/presentation/VoteController.java
Bookmark 컨트롤러, dto 클래스에 @Tag, @Schema, @Operation을 사용하여 문서화 했습니다.
@ApiResponse 응답 처리 (필요시)
closes #90
> 북마크 기능 스웨거에 추가

- src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
> 댓글 기능 단위 테스트 코드 수정 및 통과 완료

- src/main/java/balancetalk/module/file/application/FileService.java
- src/main/java/balancetalk/module/file/presentation/FileController.java
- 예외 처리 구현
- 테스트 코드 작성
closes #101
> 파일 다운로드 기능 구현 완료

- src/main/java/balancetalk/module/member/domain/Member.java
- src/main/java/balancetalk/module/member/dto/JoinDto.java
- src/main/java/balancetalk/module/member/presentation/MemberController.java
멤버 Entity에서 ip 필드를 제거했습니다.
closes #137
> 회원 정보에서 ip 제거

- src/main/java/balancetalk/module/bookmark/presentation/BookmarkController.java
- src/test/java/balancetalk/module/bookmark/application/BookmarkServiceTest.java
- src/test/java/balancetalk/module/vote/application/VoteServiceTest.java
BookmarkServiceTest 파일의 위치가 `balancetalk.module.post.application`에 있어서 컴파일 에러가 발생했습니다.
따라서 해당 파일의 위치를 `balancetalk.module.bookmark.application`에 위치시켰습니다.
그리고나서 투표 생성 기능에서 발생할 수 있는 여러 예외 상황에 대한 단위 테스트를 작성했습니다.
중복 코드로 인해 테스트 코드가 점점 지저분해지고 있음을 느꼈습니다.
따라서 `@Nested`를 사용한 계층 구조의 테스트 코드로 개선할 예정입니다.
closes #155
> 투표 생성 기능 단위 테스트 작성

- src/test/java/balancetalk/module/vote/application/VoteServiceTest.java
투표 현황 조회 및 투표 수정 기능에서 발생할 수 있는 다양한 예외 상황에 대한 단위 테스트를 작성했습니다.
closes #160
> 투표 현황 조회 및 투표 수정 기능에 대한 단위 테스트 작성

- src/main/java/balancetalk/global/exception/ErrorCode.java
- src/main/java/balancetalk/module/post/application/PostService.java
- src/main/java/balancetalk/module/post/domain/Post.java
- src/main/java/balancetalk/module/post/presentation/PostController.java
> 불필요한 파라미터 제거 및 에러코드 추가

- src/test/java/balancetalk/module/member/application/MemberServiceTest.java
`memberId`로 기존에 정보 수정, 삭제 같은 기능을 수행하다가 jwt 토큰으로 변경한 것에 대한 테스트 코드를 작성했습니다. 
추가된 로그아웃 기능은, `Redis`에 저장된 데이터의 유무에 따라서 테스트를 설계했습니다. 
기존에 매번 Join이나 Login에 대한 정보를 재설정 해줬는데, 
미리 선언해두니 코드가 전보다 더 간결해 졌습니다.
왜 로그아웃 실패만 시간이 좀 걸릴까요? 🤔
closes #158
> 멤버 서비스 클래스 단위 테스트 추가 및 예외 테스트 추가

- build.gradle
- src/main/java/balancetalk/global/config/EmbeddedRedisConfig.java
- src/main/java/balancetalk/global/config/RedisConfig.java
- src/main/java/balancetalk/module/member/application/MemberService.java
- src/test/java/balancetalk/module/member/application/MemberServiceTest.java
Embedded Redis를 사용하면 Redis를 설치하지 않고도 실행 및 테스트가 가능합니다. 
https://hongdosan.tistory.com/375
closes #217
> Embedded Redis 적용

- src/main/java/balancetalk/global/exception/ErrorCode.java
- src/main/java/balancetalk/module/authmail/application/MailService.java
- src/main/java/balancetalk/module/authmail/presentation/MailController.java
- src/main/java/balancetalk/module/member/domain/MemberRepository.java
- src/test/java/balancetalk/module/authmail/application/MailServiceTest.java
회원 가입 한 회원의 이메일로 임시 비밀번호가 발송되고 나면, 암호화가 되어 기존 비밀번호가 변경됩니다.
미 회원 가입된 이메일로 임시 비밀번호가 전송되지 않습니다.
closes #200
> 비밀번호 찾기 기능 구현

- src/main/java/balancetalk/module/post/dto/BalanceOptionResponse.java
> 게시글 응답에 각 선택지 ID 추가

- src/main/java/balancetalk/global/exception/ErrorCode.java
- src/main/java/balancetalk/module/member/presentation/MyPageController.java
- src/main/java/balancetalk/module/notice/presentation/NoticeController.java
공지사항 전체 조회, 마이페이지 게시글, 댓글 조회 시 페이지네이션에서 페이지 시작 번호를 1에서 0으로 수정했습니다.
closes #237
> 공지사항, 마이페이지 시작 페이지 번호 수정 완료

- src/main/java/balancetalk/module/comment/application/CommentService.java
- src/main/java/balancetalk/module/comment/domain/CommentRepository.java
- src/main/java/balancetalk/module/comment/dto/CommentResponse.java
- src/main/java/balancetalk/module/comment/dto/ReplyResponse.java
- src/main/java/balancetalk/module/comment/presentation/CommentController.java
답글만 응답하는 ReplyResponse 클래스를 작성하고, 기존 댓글 조회 기능과 같이 회원 비회원 여부에 따라 다른 응답을 반환하도록 기능을 구현했습니다.
```java
public List<ReplyResponse> findAllReplies(Long postId, Long parentId, String token) {
validatePostId(postId);
List<Comment> replies = commentRepository.findAllByPostIdAndParentId(postId, parentId);
if (token == null) {
return replies.stream()
.map(reply -> ReplyResponse.fromEntity(reply, null, false))
.collect(Collectors.toList());
} else {
Member member = getCurrentMember(memberRepository);
return replies.stream()
.map(reply -> {
boolean myLike = member.hasLikedComment(reply);
Optional<Vote> voteForComment = voteRepository.findByMemberIdAndBalanceOption_PostId(
reply.getMember().getId(), postId);
Long balanceOptionId = voteForComment.map(Vote::getBalanceOption).map(BalanceOption::getId) …
```
> 답글 조회 API 구현 완료

- src/main/java/balancetalk/module/post/application/PostService.java
- src/main/java/balancetalk/module/post/domain/Post.java
- src/main/java/balancetalk/module/post/presentation/PostController.java
작성일(createdAt)과 조회수(views)를 기준으로 정렬하는 것처럼 likes를 쿼리 파라미터로 전달하여 내림차순으로 정렬하도록 API를 호출했더니, 다음과 같이 이상한 결과가 나왔습니다.
그래서 SQL은 어떻게 생성되었는지 로그를 통해 확인했습니다.
```sql
select p1_0.post_id, p1_0.category, p1_0.created_at, ...
from post p1_0 left join post_like l1_0 on p1_0.post_id=l1_0.post_id 
order by l1_0.post_like_id desc
limit ?,?
```
보이는 것과 같이 likes.size가 아닌 post_like_id를 기준으로 정렬하고 있었습니다.
즉, 정렬 기준이 특정 테이블의 컬럼이어야 정상적으로 정렬되는 듯 합니다.
그래서 다양한 방법을 생각했으나 여러 이유로 폐기하였고, 최종적으로 hibernate에서 제공하는 @Formula 어노테이션을 사용하게 되었습니다.
다음과 같이 long 타입의 likesCount라는 변수를 Post 엔티티에 작성하고, @Formula로 서브쿼리를 지정합니다.
이때 서브 쿼리는 POST_LIKE 테이블에서 특정 게시글 ID와 동일한 튜플들의 개수를 count하도록 작성했습니다.
```java
public class Post extends BaseTimeEntity {
...
@OneToMany(mappedBy = "post")
private List<PostLike> likes = new ArrayList<>();
@Formula("(select …
```
> 게시글 목록 조회 시 추천수를 기준으로 내림차순 정렬하는 기능 구현

- src/main/java/balancetalk/global/jwt/JwtAuthenticationEntryPoint.java
- src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
서버에는 올바르게 메세지를 전달했으나, 클라이언트에는 항상
위와 같은 메세지를 전달했습니다.
수정된 코드로 인해서, 세가지 에러 케이스를 구분할 수 있게 되었습니다.
closes #256
> 클라이언트에 올바르게 토큰 에러 정보를 보여주도록 수정

- src/main/java/balancetalk/module/post/dto/PostRequest.java
> 게시글 작성 할때 데드라인에서 @JsonFormat 수정

- src/main/java/balancetalk/global/exception/ErrorCode.java
- src/main/java/balancetalk/module/comment/application/CommentService.java
- src/main/java/balancetalk/module/post/application/PostService.java
- src/main/java/balancetalk/module/report/domain/ReportRepository.java
> 게시글, 댓글 신고 예외 처리 추가

- src/main/java/balancetalk/global/config/SecurityConfig.java
- src/main/java/balancetalk/module/member/application/MemberService.java
- src/main/java/balancetalk/module/member/dto/ProfileResponse.java
- src/main/java/balancetalk/module/member/presentation/MemberController.java
회원 프로필을 눌렀을 때 필요한 회원 정보를 구현
회원 이미지 사진도 가져오도록 수정했습니다!! 
closes #293
> 회원 프로필 조회 기능 구현

- src/main/java/balancetalk/module/post/domain/Post.java
- src/main/java/balancetalk/module/post/dto/PostResponse.java
- src/test/java/balancetalk/module/post/application/PostServiceTest.java
게시글 조회 응답 DTO에 마감 여부 필드를 추가함에 따라 테스트 코드를 수정했습니다.
closes #314
> 게시글 관련 테스트 코드 수정

- src/main/java/balancetalk/module/member/presentation/MemberController.java
- src/main/java/balancetalk/module/post/presentation/PostController.java
> 요청 파라미터에 대한 swaager 설정 추가

- src/main/java/balancetalk/module/member/dto/MemberResponse.java
- src/main/java/balancetalk/module/member/presentation/MyPageController.java
- src/main/java/balancetalk/module/notice/presentation/NoticeController.java
- src/main/java/balancetalk/module/post/dto/GameRequest.java
- src/main/java/balancetalk/module/post/dto/GameResponse.java
- src/main/java/balancetalk/module/post/dto/TalkRequest.java
- src/main/java/balancetalk/module/post/dto/TalkResponse.java
- src/main/java/balancetalk/module/post/presentation/GameController.java
- src/main/java/balancetalk/module/post/presentation/PostController.java
- src/main/java/balancetalk/module/post/presentation/TalkController.java
- src/main/java/balancetalk/module/vote/Option.java
> 톡픽, 밸런스 게임 Swagger 문서 작성 및 회원 조회 응답값 수정

- src/main/java/balancetalk/global/common/ApiResponse.java
공통 응답 포맷을 만듬으로써, API를 사용하는 클라이언트(프론트엔드 개발자)는 일관된 구조로 응답을 받을 수 있어 디버깅 및 유지보수가 쉬워진다는 이점을 취할 수 있을 것으로 기대됩니다.
또한 이와 같은 공통 응답 포맷을 여러 API에서 재사용할 수 있게 되며, 이를 통해 개발 시간을 단축할 수 있을 것입니다.
closes #334
> 공통 응답 포맷 클래스 작성

- build.gradle
기존 local 환경에서 사용하던 H2를 MySQL로 변경했습니다.
그에 따른 설정 코드를 추가/수정했습니다.
1. local PC에 설치된 MySQL을 실행한 뒤, 'pikko'라는 이름의 데이터베이스를 생성합니다.
`create database pikko;`
2. IntelliJ에서 다음과 같이 환경 변수를 설정합니다.
closes #340
> local 환경 DB를 H2에서 MySQL로 변경

- src/main/java/balancetalk/BalanceTalkApplication.java
- src/main/java/balancetalk/global/config/SecurityConfig.java
임시로 생성한 `http://localhost:8081/games/test` URL에 대해서
수정 전
수정 후
closes #343
> 모든 URL에 대해서 시큐리티 접근 허용하도록 수정

- src/main/java/balancetalk/like/domain/Like.java
- src/main/java/balancetalk/like/domain/LikeType.java
- src/main/java/balancetalk/module/member/domain/Member.java
- src/main/java/balancetalk/talkpick/domain/TalkPick.java
- src/main/java/balancetalk/talkpick/domain/TalkPickFile.java
- src/main/java/balancetalk/talkpick/domain/TalkPickLike.java
- src/main/java/balancetalk/talkpick/domain/ViewStatus.java
- src/main/java/balancetalk/vote/domain/Vote.java
- src/main/java/balancetalk/vote/domain/VoteOption.java
TalkPick, TalkPickFile 등 톡픽 관련 엔티티 클래스를 작성했습니다.
closes #339
> 톡픽 관련 엔티티 클래스 작성

- src/main/java/balancetalk/game/domain/Game.java
- src/main/java/balancetalk/vote/domain/Vote.java
- src/main/java/balancetalk/vote/domain/VoteType.java
투표 관련 엔티티 클래스를 작성했습니다.
closes #348
> 투표 관련 엔티티 클래스 작성

- src/main/java/balancetalk/game/dto/GameDetailResponse.java
- src/main/java/balancetalk/game/dto/GameRequest.java
- src/main/java/balancetalk/game/dto/GameResponse.java
- src/main/java/balancetalk/game/presentation/GameBookmarkController.java
- src/main/java/balancetalk/game/presentation/GameController.java
- src/main/java/balancetalk/global/common/ApiResponse.java
> API 명세서 업데이트 (게임, 북마크)

- src/main/java/balancetalk/comment/application/CommentService.java
- src/main/java/balancetalk/comment/domain/Comment.java
- src/main/java/balancetalk/comment/domain/CommentRepository.java
- src/main/java/balancetalk/comment/dto/CommentDto.java
- src/main/java/balancetalk/comment/presentation/CommentController.java
- src/main/java/balancetalk/global/common/ApiResponse.java
- src/main/java/balancetalk/like/domain/Like.java
- src/main/java/balancetalk/like/domain/LikeType.java
- src/main/java/balancetalk/member/domain/Member.java
- src/main/java/balancetalk/talkpick/domain/TalkPick.java
- src/main/java/balancetalk/talkpick/domain/TalkPickRepository.java
- src/main/java/balancetalk/vote/domain/VoteRepository.java
컨벤션에 따라 기존의 CommentResponse, CommentRequest를 CommentDto의 Inner Class로 만들었습니다.
그리고 댓글 기본 CRUD 기능을 재작성했고, 이외의 기능들은 현재 Vote, Like 기능들이 완성되지 않았기 때문에 임시로 주석처리 했습니다.
Controller에서는 공통 ApiResponse를 적용했습니다.
1. 스웨거 업데이트
2. 미구현 기능들 (답글, 좋아요 등) 구현
3. 예외처리
4. 테스트코드 작성
closes #333
> 댓글, 답글 작성 / 수정 / 삭제 리팩토링 완료

- src/main/java/balancetalk/bookmark/domain/Bookmark.java
- src/main/java/balancetalk/bookmark/presentation/BookmarkGameController.java
- src/main/java/balancetalk/talkpick/domain/TalkPick.java
변경된 ERD에 따라 북마크 엔티티와 톡픽 엔티티의 연관관계를 제거하고, 리소스 ID를 추가했습니다.
closes #400
> 변경된 ERD에 따라 북마크 엔티티 수정

- src/main/java/balancetalk/file/application/FileService.java
- src/main/java/balancetalk/file/domain/s3/S3ImageRemover.java
- src/main/java/balancetalk/file/domain/s3/S3ImageUploader.java
- src/main/java/balancetalk/file/domain/s3/S3ImageUrlGetter.java
- src/test/java/balancetalk/file/domain/FileProcessorTest.java
- src/test/java/balancetalk/file/domain/s3/S3ImageRemoverTest.java
- src/test/java/balancetalk/file/domain/s3/S3ImageUploaderTest.java
- src/test/java/balancetalk/file/domain/s3/S3ImageUrlGetterTest.java
Mockito를 사용하여 이미지 업로드 기능에 사용되는 객체들의 단위 테스트를 진행했습니다.
closes #403
> 이미지 업로드 기능 단위 테스트

- src/main/java/balancetalk/talkpick/domain/Summary.java
- src/main/java/balancetalk/talkpick/domain/TalkPick.java
- src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
- src/test/java/balancetalk/talkpick/domain/TalkPickReaderTest.java
톡픽 상세 조회 기능에 대한 단위 테스트를 작성했습니다.
closes #417
> 톡픽 상세 조회 기능에 대한 단위 테스트 작성

- src/test/java/balancetalk/vote/application/VoteTalkPickServiceTest.java
- src/test/java/balancetalk/vote/domain/VoteTest.java
톡픽 투표 기능에 대한 단위 테스트를 작성했습니다.
closes #425
> 톡픽 투표 기능 단위 테스트

- src/main/java/balancetalk/bookmark/domain/Bookmark.java
- src/main/java/balancetalk/game/application/GameService.java
- src/main/java/balancetalk/game/domain/Game.java
- src/main/java/balancetalk/game/domain/repository/GameRepository.java
- src/main/java/balancetalk/game/domain/repository/GameTopicRepository.java
- src/main/java/balancetalk/game/dto/GameDto.java
- src/main/java/balancetalk/game/presentation/GameController.java
- src/main/java/balancetalk/game/presentation/GameTopicController.java
- src/main/java/balancetalk/global/exception/ErrorCode.java
- src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java
- src/main/java/balancetalk/member/domain/Member.java
- src/main/java/balancetalk/vote/application/VoteTalkPickService.java
- src/main/java/balancetalk/vote/domain/Vote.java
밸런스 게임 주제를 추가할 때 이런식으로 이름값을 보내주면 됩니다.
밸런스 게임 주제가 존재할 때, 성공적으로 게임을 생성합니다.
존재하지 않는 밸런스 게임 주제인 경우, 에러를 던져줍니다.
게임 상세 조회 시 응답값입니다. 투표 부분은 아직 미구현 상태라 null을 리턴하도록 구현했습니다.
closes #416
> 밸런스 게임 API 구현

- src/main/java/balancetalk/comment/presentation/CommentController.java
- src/main/java/balancetalk/like/presentation/LikeController.java
```java
@PostMapping
@Operation(summary = "댓글 좋아요", description = "commentId에 해당하는 댓글에 좋아요를 활성화합니다.")
public void likeComment(@PathVariable Long commentId, @PathVariable Long talkPickId, @Parameter(hidden = true) @AuthPrincipal ApiMember apiMember) {
commentLikeService.likeComment(commentId, talkPickId, apiMember);
}
```
위와 같이 `@Parameter(hidden = true)` 어노테이션을 추가하여 스웨거에서 해당 부분을 숨김처리 했습니다.
closes #428
> 댓글, 댓글 좋아요 스웨거에 ApiMember, GuestOrApiMember hidden 처리 완료

- src/main/java/balancetalk/comment/domain/Comment.java
- src/main/java/balancetalk/global/exception/ErrorCode.java
- src/main/java/balancetalk/report/application/ReportCommentService.java
- src/main/java/balancetalk/report/domain/Report.java
- src/main/java/balancetalk/report/domain/ReportReason.java
- src/main/java/balancetalk/report/domain/ReportRepository.java
- src/main/java/balancetalk/report/domain/ReportType.java
- src/main/java/balancetalk/report/dto/ReportDto.java
```java
public enum ReportReason {
욕설, 도배_및_스팸, 불건전_및_불법_정보, 차별적_발언, 홍보, 개인정보_노출_및_침해, 기타;
@JsonCreator
public static ReportReason from(String value) {
for (ReportReason reason : ReportReason.values()) {
if (reason.name().equals(value)) {
return reason;
}
}
throw new BalanceTalkException(INVALID_REPORT_REASON);
}
@JsonValue
public String toValue() {
return this.name();
}
}
```
기능명세서에 따라 신고 사유를 사용자 직접 입력이 아닌 선택을 할 수 있도록 Enum 처리 하였고, 역직렬화 문제를 방지하기 위한 코드를 작성했습니다.
기존의 `ReportType` 또한 역직렬화 문제를 해결하기 위한 코드를 추가했습니다.
1. 갑자기 든 생각인데, 검증 부분을 서비스 레이어에서 처리하는 게 맞는가- 라는 생각이 들었습니다. 응집도를 높이기 위해 검증 메서드는 해당 엔티티들 또는 별도의 Validator 클래스로 이동이 되어야 할까요?
2. 처리하지 못한 예외가 있을까요? 
closes #430
> 신고 기능 추가 구현 완료

- src/test/java/balancetalk/bookmark/application/BookmarkTalkPickServiceTest.java
- src/test/java/balancetalk/bookmark/domain/BookmarkGeneratorTest.java
- src/test/java/balancetalk/talkpick/domain/TalkPickValidatorTest.java
> 톡픽 북마크 기능 단위 테스트

- src/main/java/balancetalk/bookmark/domain/repository/BookmarkRepositoryCustom.java
- src/main/java/balancetalk/bookmark/domain/repository/BookmarkRepositoryImpl.java
- src/main/java/balancetalk/talkpick/application/TalkPickService.java
- src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryCustom.java
- src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
- src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
- src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
테스트를 통해 다음과 같이 잘 정렬되는 것을 확인하였습니다.
closes #457
> 톡픽 목록 조회 기능 구현

- src/main/java/balancetalk/game/application/GameService.java
- src/main/java/balancetalk/game/domain/Game.java
- src/main/java/balancetalk/game/domain/GameReader.java
- src/main/java/balancetalk/game/dto/GameDto.java
- src/main/java/balancetalk/global/jwt/GuestOrApiMemberArgumentResolver.java
- src/main/java/balancetalk/member/dto/GuestOrApiMember.java
- src/main/java/balancetalk/vote/application/VoteGameService.java
- src/main/java/balancetalk/vote/dto/VoteGameDto.java
- src/main/java/balancetalk/vote/presentation/VoteGameController.java
투표 생성 시, 이런식으로 A, B 투표 수를 조회할 수 있습니다.
closes #472
> 밸런스 게임 투표 작업

- src/main/java/balancetalk/bookmark/domain/BookmarkRepository.java
- src/main/java/balancetalk/member/application/MyPageService.java
- src/main/java/balancetalk/member/presentation/MyPageController.java
- src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java
- src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
- src/main/java/balancetalk/vote/domain/VoteRepository.java
저장한 톡픽 조회, 북마크 삭제 후 조회, 삭제한 북마크를 다시 추가 후 조회,
투표한 톡픽 조회, 투표 수정 후 조회, 투표 삭제 후 조회, 삭제한 투표를 다시 투표 후 조회 모두 확인했습니다.
```java
public interface BookmarkRepository extends JpaRepository<Bookmark, Long> {
@Query("SELECT b FROM Bookmark b WHERE b.member.id = :memberId AND b.bookmarkType = :bookmarkType AND b.active = true ORDER BY b.lastModifiedAt DESC")
List<Bookmark> findAllByMemberIdDesc(@Param("memberId") Long memberId, @Param("bookmarkType") BookmarkType bookmarkType);
}
```
```java
@Query("SELECT v FROM Vote v WHERE v.member.id = :memberId AND v.talkPick IS NOT NULL ORDER BY v.lastModifiedAt DESC")
List<Vote> findAllByMemberIdDesc(Long memberId);
```
만약 투표를 수정 할 때에는 내림차순 재정렬이 적용되지 않는다면, 수정일 기준이 아닌 생성일 기준으로 수정해야 합니다.
closes #476
> 마이페이지 - 내가 저장한, 투표한 톡픽 조회 구현

- src/main/java/balancetalk/bookmark/domain/BookmarkRepository.java
- src/main/java/balancetalk/comment/domain/CommentRepository.java
- src/main/java/balancetalk/member/application/MyPageService.java
- src/main/java/balancetalk/member/presentation/MyPageController.java
- src/main/java/balancetalk/talkpick/domain/TalkPick.java
- src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java
- src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
- src/main/java/balancetalk/vote/domain/VoteRepository.java
```java
@Query("SELECT c FROM Comment c WHERE c.member.id = :memberId AND c.talkPick IS NOT NULL " +
"AND c.lastModifiedAt IN (SELECT MAX(c2.lastModifiedAt) FROM Comment c2 WHERE c2.member.id = :memberId GROUP BY c2.talkPick.id) " +
"ORDER BY c.lastModifiedAt DESC")
List<Comment> findAllByMemberIdDesc(@Param("memberId") Long memberId);
```
1. 북마크 추가/삭제 동작, 조회수 등에에 따라 해당 톡픽의 last_modified_at이 업데이트 되지 않도록 수정
2. 또는 다른 방법 사용
closes #480
> 마이페이지 - 내가 댓글단, 작성한 톡픽 조회 기능 구현 완료

- src/main/java/balancetalk/bookmark/application/BookmarkGameService.java
- src/main/java/balancetalk/bookmark/presentation/BookmarkGameController.java
- src/main/java/balancetalk/game/domain/Game.java
- src/main/java/balancetalk/member/domain/Member.java
1. `gameId`로부터 game 존재 여부 확인
2. 주어진 토큰 값으로 인가 여부 확인
3. 자기가 생성한 게임인 경우 예외처리
4. 이미 북마크를 한 게임인 경우 예외처리
5. 회원이 북마크를 한 목록을 순회하여 해당 `gameId`와 `game`으로 조회.
5-1. 만약에 존재하지 않으면, DB에 저장
5-2. 존재 한다면, 북마크를 `active`로 설정
6. 북마크 카운트 + 1
북마크 생성이 된 모습
1. `gameId`로부터 game 존재 여부 확인
2. 주어진 토큰 값으로 인가 여부 확인
3. 회원이 북마크를 한 목록을 순회하여 해당 `gameId`와 `game`으로 조회하여 없는 경우 예외처리
4. 북마크가 `deactive` 상태라면 예외처리
5. 북마크를 `deactive` 처리
6. 북마크 카운트 -1
closes #486
> 밸런스 게임 북마크 API 작업

- .github/workflows/cd.yml
> aws 인프라 재구성

- src/main/resources/logs/log4j2-dev.yml
> 로그 파일 네이밍 변경

- src/main/java/balancetalk/file/domain/FileType.java
- src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java
- src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java
- src/main/java/balancetalk/member/domain/Member.java
- src/main/java/balancetalk/talkpick/application/TalkPickService.java
- src/main/java/balancetalk/talkpick/application/TempTalkPickService.java
- src/main/java/balancetalk/talkpick/domain/TalkPick.java
- src/main/java/balancetalk/talkpick/domain/TempTalkPick.java
- src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
- src/main/java/balancetalk/talkpick/dto/TempTalkPickDto.java
임시 저장했던 톡픽이 존재하는 경우와 그렇지 않은 경우를 구분하여 구현했습니다.
- 임시 저장했던 톡픽이 존재하는 경우, 해당 임시 톡픽을 새로운 정보로 업데이트한 후 관련 이미지의 resourceId를 업데이트합니다.
- 임시 저장했던 톡픽이 존재하지 않는 경우, 새로운 임시 톡픽을 저장한 후 관련 이미지의 resourceId를 업데이트합니다.
```java
@Transactional
public void createTempTalkPick(SaveTempTalkPickRequest request, ApiMember apiMember) {
Member member = apiMember.toMember(memberRepository);
if (member.hasTempTalkPick()) {
Long prevTempTalkPickId = member.updateTempTalkPick(request.toEntity(member));
fileRepository.updateResourceIdByStoredNames(prevTempTalkPickId, request.getStoredNames());
return;
}
TempTalkPick savedTempTalkPick = tempTalkPickRepository.save(request.toEntity(member));
fileRepository.updateResourceIdByStoredNames(savedTempTalkPick.getId(), request.getStoredNames());
}
```
closes #515
> [톡픽 임시 저장 API] 이미지 관련 정보 추가

- src/main/java/balancetalk/file/application/FileService.java
- src/main/java/balancetalk/file/domain/File.java
- src/main/java/balancetalk/file/domain/repository/FileRepository.java
- src/main/java/balancetalk/file/presentation/FileController.java
다음과 같이 정상적으로 제거되는 것을 확인했습니다.
closes #517
> 이미지 제거 기능 구현

- src/main/java/balancetalk/member/presentation/Oauth2Controller.java
> 소셜 로그인 api 추가

- build.gradle
- src/main/java/balancetalk/comment/application/CommentService.java
- src/main/java/balancetalk/global/notification/application/NotificationService.java
- src/main/java/balancetalk/global/notification/domain/Notification.java
- src/main/java/balancetalk/global/notification/domain/NotificationMessage.java
- src/main/java/balancetalk/global/notification/domain/NotificationTitleCategory.java
- src/main/java/balancetalk/global/notification/dto/NotificationDto.java
- src/main/java/balancetalk/like/application/CommentLikeService.java
기존에 `"톡픽"` 형태로 작성했던 알림 카테고리를 상황에 맞춰 사용할 수 있도록 `NotificationTitleCategory` 클래스로 만들었습니다.
```java
@Getter
@RequiredArgsConstructor
public enum NotificationTitleCategory {
WRITTEN_TALK_PICK("내가 작성한 톡픽"),
OTHERS_TALK_PICK("톡픽"),
WRITTEN_GAME("내가 만든 밸런스게임"),
OTHERS_GAME("밸런스게임");
...
```
좋아요 개수가 100개, 200개, 100 * n개... 인 경우와
좋아요 개수가 1000개, 2000개, 1000 * n개... 인 경우에도 알림을 출력하도록 구현했습니다.
그리고 좋아요 100개, 1000개 달성 시에 배찌 획득 알림도 울리도록 구현했습니다. 현재 중복 알림 방지는 한 댓글의 `likeCount` 를 기준으로 처리되고 있어서, 따로 메서드를 분리하는 것 보다 이중 if문으로 작성하는 것이 효율적이라고 생각했습니다.
```java
boolean isMilestoneLike = (likeCount == FIRST_COUNT_OF_LIKE_NOTIFICATION ||
likeCount == SECOND_COUNT_OF_LIKE_NOTIFICATION ||
likeCount == THIRD_COUNT_OF_LIKE_NOTIFICATION ||
(likeCount > THIRD_COUNT_OF_LIKE_NOTIFICATION && likeCount % …
```
> 기존 알림 기능 개선 완료

- src/main/java/balancetalk/bookmark/presentation/BookmarkGameController.java
- src/main/java/balancetalk/bookmark/presentation/BookmarkTalkPickController.java
> memberId 필드가 보이지 않도록 수정

- src/main/java/balancetalk/global/utils/LoggingAspect.java
로그인 상태에서 GuestOrApi를 호출했을 때 memberId=? 이런 형태가 아닌 GUEST로 로그가 찍히는 오류가 있어서 수정했습니다.
수정 후 
> 로그인 상태
[REQUEST] 0:0:0:0:0:0:0:1 **memberId=1** GET /games/1 args=[1, GuestOrApiMember(memberId=1)]
[RESPONSE] 200 GameDto.GameDetailResponse(id=1, title=제목, description=추가설명, tag=ㅇㅇ, gameOptions=[GameOptionDto(name=옵션1, imgUrl=~~~, description=?, optionType=A), GameOptionDto(name=옵션2, imgUrl=~~~, description=?, optionType=B)], views=1, votesCountOfOptionA=0, votesCountOfOptionB=0, myBookmark=false, votedOption=null, gameTopic=커플)
> 로그아웃 상태
[REQUEST] 0:0:0:0:0:0:0:1 GUEST GET /games/1 args=[1, GuestOrApiMember(memberId=-1)]
[RESPONSE] 200 GameDto.GameDetailResponse(id=1, title=제목, description=추가설명, tag=ㅇㅇ, gameOptions=[GameOptionDto(name=옵션1, imgUrl=~~~, description=?, optionType=A), …
> GuestOrAPi 에서도 memberId를 가져오도록 수정

- src/main/java/balancetalk/game/application/GameService.java
- src/main/java/balancetalk/game/domain/repository/GameTagRepository.java
- src/main/java/balancetalk/game/presentation/GameTagController.java
- src/main/java/balancetalk/global/exception/ErrorCode.java
> URL에서 대문자 대신 하이픈으로 수정

- src/main/java/balancetalk/global/notification/dto/NotificationDto.java
- src/main/java/balancetalk/global/notification/presentation/NotificationController.java
알림 기능 응답 시 톡픽 뿐만 아니라 밸런스게임의 제목도 반환될 수 있으므로, 그에 맞게 네이밍을 수정했습니다.
closes #575
> 알림 기능 응답 필드 수정 완료

- src/main/java/balancetalk/talkpick/application/TalkPickService.java
- src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
톡픽 상세 조회 응답에 storedName 추가
closes #581
> 톡픽 상세 조회 응답에 이미지 storedName 추가

- src/main/resources/logs/log4j2-dev.yml
> 로그 시간을 한국 시간대로 표시되도록 수정

- src/main/java/balancetalk/comment/application/CommentService.java
```java
private boolean isCommentMyLiked(Long commentId, GuestOrApiMember guestOrApiMember) {
if (guestOrApiMember.isGuest()) {
return false;
}
Long memberId = guestOrApiMember.toMember(memberRepository).getId();
if (likeRepository.existsByResourceIdAndMemberId(commentId, memberId)) {
return likeRepository.findByResourceIdAndMemberId(commentId, memberId)
.orElseThrow(() -> new BalanceTalkException(NOT_FOUND_LIKE))
.getActive();
}
return false;
}
```
`myLike` 값 설정 로직을 변경했습니다. 기존에는 해당 `Like` 객체가 존재하는지 여부를 그대로 `myLike` 에 할당했으나,  해당 `Like` 객체가 존재한다면, 그 `Like` 객체의 `active` 값을 myLike 에 할당함으로서 해결했습니다.
closes #587
> 댓글 좋아요 취소 후 myLike 필드의 값이 변경되지 않는 에러 해결

- src/main/java/balancetalk/game/application/GameService.java
- src/main/java/balancetalk/game/dto/GameDto.java
- src/main/java/balancetalk/game/dto/GameSetDto.java
- src/main/java/balancetalk/game/presentation/GameController.java
조회할 때, `ConcurrentHashMap`을 사용하여 게임에 해당하는 사용자의 게임 북마크, 투표 여부를 조회할 수 있도록 구현했습니다.
Game 리스트를 순회하면서, 북마크 표시가 되어있다면 true, 없다면 false를 `bookmarkMap`에 저장했습니다. 
투표 여부는, `myVote`가 존재하는 경우에만 해당 값을 `voteOptionMap`에 넣어주었습니다. 존재하지 않는 경우엔 null을 기본값으로 가지고 있기 떄문에 따로 체크해주지 않았습니다.
로그인 된 경우에 토큰값으로 조회하면 본인 투표, 북마크 이력을 확인할 수 있습니다.
closes #591
> 밸런스 세트 조회 로직 수정

- src/main/java/balancetalk/member/dto/MemberDto.java
> refactor: 회원 조회 시 프로필 이미지 필드 추가

- src/main/java/balancetalk/game/application/SearchGameService.java
- src/main/java/balancetalk/game/domain/repository/GameRepository.java
- src/main/java/balancetalk/game/dto/SearchGameResponse.java
- src/main/java/balancetalk/game/presentation/SearchGameController.java
```java
@Query(value = "SELECT DISTINCT g.* " +
"FROM game g " +
"LEFT JOIN game_set gs ON g.game_set_id = gs.id " +
"LEFT JOIN game_option go ON go.game_id = g.id " +
"WHERE " +
"gs.sub_tag = :query OR " +
"g.title = :query OR " +
"g.description = :query OR " +
"go.name = :query OR " +
"go.description = :query",
nativeQuery = true)
List<Game> searchExactMatch(@Param("query") String query);
@Query(value = "SELECT DISTINCT g.* " +
"FROM game g " +
"INNER JOIN game_set gs ON g.game_set_id = gs.id " +
"INNER JOIN game_option go ON go.game_id = g.id " +
"WHERE " +
"MATCH(gs.sub_tag) AGAINST (:query IN NATURAL LANGUAGE MODE) OR " +
"MATCH(g.title, g.description) AGAINST (:query IN NATURAL LANGUAGE MODE) OR " +
"MATCH(go.name, go.description) AGAINST (:query IN NATURAL LANGUAGE MODE)", …
```
> 밸런스게임 검색 구현 완료

- src/main/java/balancetalk/file/application/FileService.java
- src/main/java/balancetalk/global/exception/ErrorCode.java
하나라도 실패하면 전체를 중단하고 롤백해야 한다는 의미를 명확히 전달하고자, 업로드 예외 처리 범위를 전체 파일로 변경했습니다.
closes #628
> 이미지 업로드 예외 처리 범위를 전체 파일로 변경

- src/main/java/balancetalk/global/oauth2/CustomSuccessHandler.java
> redirect url 주소를 3000포트에서 public ip주소로 변경

- src/main/java/balancetalk/game/application/GameService.java
에러가 발생한 로직은 아래와 같습니다.
```java
GameBookmark gameBookmark = gameBookmarkRepository.findByMemberAndGameSetId(member, gameSetId)
.orElseThrow(() -> new BalanceTalkException(NOT_FOUND_BOOKMARK));
```
밸런스게임 세트 조회 로직에서 해당 밸런스게임 세트 id와 멤버로 북마크를 찾는 로직인데, 해당 밸런스게임 세트에서 북마크를 한 적이 없을 경우 예외처리로 인해 조회가 불가능한 상황이 발생했습니다.
따라서, gameBookmark 값이 null일 가능성을 생각하고 로직을 다시 만들었습니다.
```java
ptional<GameBookmark> optionalGameBookmark = gameBookmarkRepository.findByMemberAndGameSetId(member, gameSetId);
boolean isEndGameSet = optionalGameBookmark.map(GameBookmark::getIsEndGameSet).orElse(false);
for (Game game : games) {
boolean hasBookmarked = optionalGameBookmark
.map(gameBookmark -> gameBookmark.getGameId() != null && gameBookmark.getGameId().equals(game.getId()))
.orElse(false);
bookmarkMap.put(game.getId(), …
```
> 밸런스게임 세트 조회 시 북마크 관련 에러 발생 해결

- src/main/java/balancetalk/game/application/GameService.java
- src/main/java/balancetalk/game/domain/Game.java
- src/main/java/balancetalk/game/domain/GameSet.java
- src/main/java/balancetalk/game/domain/repository/GameRepository.java
- src/main/java/balancetalk/game/dto/GameDto.java
- src/main/java/balancetalk/game/dto/GameSetDto.java
- src/main/java/balancetalk/game/dto/SearchGameResponse.java
- src/main/java/balancetalk/global/notification/dto/NotificationDto.java
기존에 제시된 플로우에 따라 `Game` 의 title 필드를 `GameSet` 으로 이동하고, 그에 영향을 받는 코드들을 수정했습니다.
closes #637
> 밸런스게임 세트에 title 필드 추가 완료

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- build.gradle
기존 SonarQube의 경우 브랜치별 분석이 원활하지 않아 SonarCloud로 마이그레이션하였습니다.
closes #640
> SonarCloud 적용

- build.gradle
- config/checkstyle/checkstyle.xml
SonarCloud만으로는 코딩 컨벤션까지 강제할 수 없기 때문에, checkstyle 플러그인을 추가하였습니다.
[[The Checkstyle Plugin](https://arc.net/l/quote/alffzgyk)](https://arc.net/l/quote/alffzgyk)
closes #642
> checkstyle 플러그인 적용

- build.gradle
> JWT 관련 의존성 변경

- src/main/java/balancetalk/global/oauth2/service/CustomOAuth2UserService.java
SonarQube에서 NPE 때문에 Reliabilty가 통과하지 못하던 이슈를 해결했습니다.
closes #648
> Nullable 값 추가

- src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
- src/main/java/balancetalk/talkpick/presentation/TempTalkPickController.java
- src/main/java/balancetalk/vote/presentation/VoteTalkPickController.java
톡픽 관련 컨트롤러 클래스에 유효성 검증 애노테이션을 추가했습니다.
closes #658
> 톡픽 관련 유효성 검증 애노테이션 추가

- src/main/java/balancetalk/game/application/SearchGameService.java
- src/main/java/balancetalk/global/exception/ErrorCode.java
```java
// 검색어가 공백이거나 2자 미만일 경우 예외 처리
if (query.isBlank()) {
throw new BalanceTalkException(BALANCE_GAME_SEARCH_BLANK);
}
if (query.replaceAll(" ", "").length() < 2) {
throw new BalanceTalkException(BALANCE_GAME_SEARCH_LENGTH);
}
```
검색어가 공백일 경우와 2자 미만일 경우를 예외 처리 했습니다.
특히 검색어 길이 예외처리에서, 사용자가 `    김` 과 같이 공백+1자 의 조합으로도 검색할 수 있으므로, **검색어의 공백을 제거했을 때 2자 미만**일 경우로 기준을 잡았습니다.
closes #661
> 밸런스게임 검색 예외처리 완료

- src/main/java/balancetalk/game/domain/Option.java
구조가 변경됨에 따라 더이상 쓰이지 않는 Enum을 제거합니다.
closes #671
> 불필요한 Enum 클래스 삭제.

- src/main/java/balancetalk/authmail/application/MailService.java
- src/main/java/balancetalk/authmail/presentation/MailController.java
회원 가입 -> 중복 회원 체크
비밀번호 재설정 -> 회원 가입 여부 체크
closes #682
> 회원 가입 인증 API, 비밀번호 재설정 API 분리

- src/main/java/balancetalk/talkpick/dto/BaseTalkPickFields.java
- src/main/java/balancetalk/talkpick/dto/SearchTalkPickResponse.java
- src/main/java/balancetalk/talkpick/dto/TempTalkPickDto.java
> TempTalkPickDto 공통 필드 분리
