src/main/java/balancetalk/global/exception/BalanceTalkException.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/global/exception/ErrorResponse.java, src/main/java/balancetalk/global/exception/GlobalExceptionHandler.java, src/main/java/balancetalk/module/member/domain/Member.java, src/main/java/balancetalk/module/post/domain/Post.java, src/main/java/balancetalk/module/vote/application/VoteService.java
회원이 투표를 진행하는 과정에서 발생할 수 있는 예외를 처리하는 기능을 구현한다.
- 제가 놓친 발생할 수 있는 예외가 있다면 알려주세요.
- 에러 코드나 메시지, 또는 enum 네이밍 중에서 수정할 부분이 있다면 알려주세요.
closes #46
=> 투표 기능 예외 처리

src/main/java/balancetalk/module/post/application/BookmarkService.java, src/main/java/balancetalk/module/post/domain/BookmarkRepository.java, src/main/java/balancetalk/module/post/presentation/BookmarkController.java
bookmark 통합 branch에서 설명
- 예외 처리 구현
- 단위 테스트
- Spring Security 도입 후 현재 인증된 사용자 정보 기반으로 북마크 목록 조회하게 변경 필요
closes #60
=> 북마크 해제 기능 구현 완료

src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/module/member/domain/Member.java, src/main/java/balancetalk/module/post/application/BookmarkService.java, src/main/java/balancetalk/module/post/domain/Post.java, src/main/java/balancetalk/module/post/presentation/BookmarkController.java
- 구현하지 않은 예외 처리가 있는지 체크해주시면 감사하겠습니다!
- 북마크 기능 단위 테스트
- 예외 처리 단위 테스트
closes #63
=> 북마크 기능 예외 처리 구현 완료

src/main/java/balancetalk/global/exception/GlobalExceptionHandler.java, src/main/java/balancetalk/module/member/application/MemberService.java, src/main/java/balancetalk/module/member/dto/JoinDto.java, src/main/java/balancetalk/module/post/application/PostService.java, src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Post 서비스 로직에 에러 코드를 추가했습니다.
closes #82
=> 게시글 CRUD 에러 코드 추가

src/main/java/balancetalk/module/comment/application/CommentService.java, src/main/java/balancetalk/module/comment/domain/Comment.java, src/main/java/balancetalk/module/comment/dto/CommentCreateRequest.java, src/main/java/balancetalk/module/comment/dto/CommentResponse.java, src/main/java/balancetalk/module/vote/domain/VoteRepository.java, src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
Comment<->BalanceOption 연관 관계를 맺어주지 않고, Vote를 활용해서 selectedOptionId를 반환하게 구현했습니다.
또한 투표한 사람만 댓글을 작성할 수 있도록 예외 처리를 구현했습니다.
closes #61
=> 댓글 조회시 selectedOptionId 반환 기능 구현 완료

src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/module/file/application/FileService.java, src/main/java/balancetalk/module/file/domain/File.java, src/main/java/balancetalk/module/file/domain/FileRepository.java, src/main/java/balancetalk/module/file/dto/FileDto.java, src/main/java/balancetalk/module/file/presentation/FileController.java
- FileDto에 팩터리 메서드 of()를 사용해서 구현했는데, 더 나은 방법이 있었을까요?
- 파일 다운로드 기능 구현
- 예외 처리 구현
- 단위 테스트 작성 및 통과
closes #88
=> 파일 업로드 기능 구현 완료

src/main/java/balancetalk/module/member/domain/Member.java, src/main/java/balancetalk/module/post/application/PostService.java, src/main/java/balancetalk/module/post/domain/Post.java, src/main/java/balancetalk/module/post/dto/PostResponseDto.java, src/main/java/balancetalk/module/post/presentation/PostController.java
API 명세서에는 존재하지만 실제 API 응답에는 누락된 필드를 추가했습니다.
회원 조회는 ID 조회로 임시 구현했습니다.
closes #119
=> 게시글 단건, 전체 조회 API 응답에 누락된 필드 추가 

src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/module/comment/application/CommentService.java, src/main/java/balancetalk/module/comment/domain/Comment.java, src/main/java/balancetalk/module/comment/dto/ReplyCreateRequest.java, src/main/java/balancetalk/module/comment/presentation/CommentController.java
- - [x] 해당 게시글이 존재하지 않는 경우 예외 처리
- - [x] 해당 원 댓글(부모 댓글)이 존재하지 않는 경우 예외 처리
- - [x] 해당 해왼이 존재하지 않는 경우 예외 처리
Comment 엔티티에 답글 관계를 구현하기 위한 parent 필드를 구현했습니다.
Comment 엔티티를 수정하지 않고 구현할 방법을 생각해봤으나, 추가적인 테이블을 만드는 것 보다는
이 방식이 추가적인 조회 API를 만들지 않아도 되기에 위와 같은 방식으로 구현했습니다.
노션 API 명세서에는 memberId 는 포함되어 있지 않으나, 프론트쪽에서 필요하다고 생각되어서 Request DTO에 추가했습니다.
1. 불필요한 구현이 있다면 확인해 주시면 감사하겠습니다!
2. Comment 엔티티를 수정하지 않으면서도 더 효율적인 구현 방식이 있었을까요?
3. 빼먹은 예외가 있다면 알려주세요!
closes #122
=> 답글 작성 기능 구현 완료

build.gradle, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/module/member/application/MemberService.java, src/main/java/balancetalk/module/member/presentation/MemberController.java, src/main/java/balancetalk/module/post/application/PostService.java
로그아웃을 하면, 사용자 이메일 값에 value로 해당하는 토큰 값이 삭제됩니다. 
로그인 한 상태에서는 성공적으로 게시글이 작성되지만,
로그아웃을 한 상태라면 `(Redis에 저장된 value가 Null일 때)` 에러를 던지도록 구현했습니다.
로그아웃을 하고, 다시 재 로그인을 할때 만료되지 않는 한 동일한 토큰 값이 다시 주어져야 하는데 매번 재발급을 하고 있어서 추후에 코드 수정이 필요합니다.
closes #143
=> 로그아웃 기능 구현

src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/module/comment/application/CommentService.java, src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
- 답글 깊이 제한 로직 추가: `CommentService` 내 `createReply` 메서드에서 답글 생성 전, 답글의 깊이를 검증하는 `validateDepth` 메서드를 호출합니다. 이를 통해 답글의 깊이가 설정된 최대 깊이(`maxDepth`)를 초과하는 경우`BalanceTalkException` 을 발생시킵니다. 추후 답글에도 답글을 달 수 있게 하거나 웹 페이지에서 최대 depth 변경시, maxDepth 값만 바꿔 주면 답글에도 답글 작성이 가능합니다.
위 사진은 application.yml의 depth를 2로 설정했을 때, 예외 처리 예시입니다.
- 테스트 코드 작성: `답글 생성 성공`, `답글에 대한 답글 생성 시도 시 예외 발생`, `잘못된 postId로 답글 생성 시도 시 예외 발생` 에 대한 테스트 코드를 작성하고 통과를 완료했습니다.
closes #139
=> 답글 depth를 1로 제한하는 기능 구현 완료

src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/module/bookmark/application/BookmarkService.java, src/main/java/balancetalk/module/comment/application/CommentService.java, src/main/java/balancetalk/module/comment/domain/CommentLike.java, src/main/java/balancetalk/module/comment/domain/CommentRepository.java, src/main/java/balancetalk/module/comment/dto/CommentResponse.java, src/main/java/balancetalk/module/comment/presentation/CommentController.java, src/test/java/balancetalk/module/comment/application/CommentServiceTest.java
댓글 수정, 삭제 메서드에 아래와 같은 로직을 추가함으로서, 해당 댓글이 URL과 일치하는 post에 속하는지 여부를 검사합니다.
```java
if (!comment.getPost().getId().equals(postId)) {
throw new BalanceTalkException(NOT_FOUND_COMMENT_AT_THAT_POST);
}
```
이를 위해 컨트롤러에서도 `@PathVariable` 로 `postId` 를 받아오게 수정했습니다.
closes #이슈번호
=> 댓글 기능 사용 시 해당 댓글이 URL의 게시글 id와 매칭 여부 검증 로직 추가 완료

src/main/java/balancetalk/global/exception/ConstraintExceptionHandler.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/module/file/domain/File.java, src/main/java/balancetalk/module/member/domain/Member.java, src/main/java/balancetalk/module/notice/application/NoticeService.java, src/main/java/balancetalk/module/notice/domain/Notice.java, src/main/java/balancetalk/module/notice/domain/NoticeRepository.java, src/main/java/balancetalk/module/notice/dto/NoticeRequest.java, src/main/java/balancetalk/module/notice/dto/NoticeResponse.java, src/main/java/balancetalk/module/notice/presentation/NoticeController.java, src/test/java/balancetalk/module/notice/application/NoticeServiceTest.java, src/test/java/balancetalk/module/notice/presentation/NoticeControllerTest.java
~~Notice 엔티티에서 제약 조건으로 걸리는 항목들을 NoticeRequest에서 예외 처리하도록 구현했습니다.
엔티티 자체에서 예외가 처리되게 하거나 핸들링하게 되면, PK_id 값을 예외가 발생할 때 마다 건너뛰게 되므로 위와 같이 구현했습니다.~~
조건문으로 처리하던 제약 조건을 DTO에 어노테이션을 추가하고, `ConstraintExceptionHandler` 클래스를 만들어 핸들링하게 수정했습니다.
1. 엔티티 자체에서 예외가 처리되고 있는 다른 기능들에 대한 예외 처리가 필요합니다.
2. 현재 공지사항 작성 시 파일 업로드는 구현하지 않았는데, 추후 구현이 필요합니다. (나머지 공지사항 기능 완성 후 구현 예정)
closes #170
=> 공지사항 작성 기능 구현 완료

src/main/java/balancetalk/module/post/application/PostService.java, src/main/java/balancetalk/module/post/domain/Post.java, src/main/java/balancetalk/module/post/dto/PostResponse.java, src/main/java/balancetalk/module/post/presentation/PostController.java
- 기존의 findById 메서드는 `@Transactional(readOnly = true)`로 되어 있었는데, 조회수가 증가하지 않았습니다. 따라서 readOnly 설정을 제거하였습니다.
- 조회하는 사용자가 ADMIN이 아닌 경우에만 조회수가 증가하도록 구현했습니다.
```java
if (member.getRole() == Role.USER) {
post.increaseViews();
}
```
closes #180
=> 게시글 조회 API에 조회수 증가 로직 추가

src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/module/member/application/MemberService.java, src/main/java/balancetalk/module/member/domain/Member.java, src/main/java/balancetalk/module/member/domain/MemberRepository.java, src/main/java/balancetalk/module/member/presentation/MemberController.java, src/test/java/balancetalk/module/member/application/MemberServiceTest.java, src/test/java/balancetalk/module/post/application/PostServiceTest.java
회원 닉네임 중복을 체크해주는 기능을 구현하고, 단위 테스트를 추가했습니다.
String 데이터를 하나만 보낼 때는 `JSON`에서 `Text`로 바꿔서 보내야 합니다. 만약에 db에 `멤버` 라는 값이 들어 있을 때, 중복 검사를 하기 위해서 JSON 형태로 `"멤버"` 값을 보내주면 따옴표 때문에 인식을 하지 못하는 문제가 발생합니다.
closes #177
=> 회원 닉네임 중복 검증 API 추가 및 테스트 코드 작성

src/main/java/balancetalk/module/comment/application/CommentService.java, src/main/java/balancetalk/module/comment/domain/CommentRepository.java, src/main/java/balancetalk/module/comment/presentation/CommentController.java, src/main/java/balancetalk/module/post/application/PostService.java, src/main/java/balancetalk/module/post/dto/PostRequest.java, src/main/java/balancetalk/module/post/presentation/PostController.java, src/test/java/balancetalk/module/comment/application/CommentServiceTest.java, src/test/java/balancetalk/module/post/application/PostServiceTest.java
게시글과 댓글 목록을 조회할 때 각각 10개의 데이터만 반환되도록 페이징 처리해주었습니다.
프론트엔드에서 페이지의 개수 등 페이지 관련 정보를 요청하셔서 반환 타입을 Page<PostResponse>, Page<CommentResponse>로 수정했습니다.
작성일 기준 정렬 처리는 해주었지만, 추천수와 조회수 기준 정렬은 아직 처리하지 못했습니다.
이는 Spring Data JPA의 Pageable 대신, 자체적으로 Pageable 객체를 구현해야 하기 때문에 보충 학습한 뒤 구현하겠습니다.
closes #190
=> 게시글, 댓글 조회 API 페이징, 정렬 처리

src/main/java/balancetalk/global/config/SecurityConfig.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/global/jwt/JwtAuthenticationEntryPoint.java, src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java, src/main/java/balancetalk/global/jwt/JwtTokenProvider.java, src/main/java/balancetalk/global/jwt/JwtUtils.java, src/main/java/balancetalk/module/authmail/application/MailService.java, src/main/java/balancetalk/module/comment/dto/CommentResponse.java, src/main/java/balancetalk/module/member/application/MemberService.java, src/main/java/balancetalk/module/member/domain/MemberRepository.java, src/main/java/balancetalk/module/post/dto/PostResponse.java, src/main/java/balancetalk/module/vote/application/VoteService.java, src/test/java/balancetalk/module/authmail/application/MailServiceTest.java, src/test/java/balancetalk/module/member/application/MemberServiceTest.java
이전에 `hasMessage` 에서 String 메세지를 입력했는데, enum의 에러 메세지를 가져오는 형태로 수정헀습니다.
인증이 필요하지 않은 URL에 대해서만 접근 가능하게 설정하고, 이외의 URL에 대해서는 미인증 시 접근 불가능하게 설정했습니다.
이전에 토큰이 만료된 경우에 서버쪽에선 에러 메세지가 정상적으로 출력이 되었지만, 클라이언트엔 단순히 500 Internal Server Error라고 표기되어 어떠한 에러인지 알 수 없었습니다.
위 에러는 스프링 시큐리티에서 발생한 에러이기 때문에, 기존에 에러 메세지를 던지던 `@RestControllerAdvice` 에서 처리가 불가능하고, 시큐리티 필터 로직에서 에러를 처리해야 했습니다.
```java
@Component
public class JwtAuthenticationEntryPoint implements AuthenticationEntryPoint {
@Override
public void commence(HttpServletRequest request, HttpServletResponse response, AuthenticationException authException) throws IOException, ServletException {
response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
response.setCharacterEncoding("utf-8");
response.setContentType("application/json");
ObjectMapper objectMapper …
```
=> 시큐리티 인증 URL 추가 및 에러 처리 추가

src/main/java/balancetalk/module/member/application/MemberService.java, src/main/java/balancetalk/module/member/domain/Member.java, src/main/java/balancetalk/module/member/dto/JoinRequest.java, src/main/java/balancetalk/module/member/dto/MemberResponse.java, src/test/java/balancetalk/module/member/application/MemberServiceTest.java
회원 가입 API 사용 시 profilePhoto 필드에 파일 이름을 입력하면 해당 파일의 id가 회원의 프로필 사진으로 등록이 됩니다. (null 가능)
DB 상에서의 프로필 사진 확인
단일 회원 조회 시에 정상적으로 프로필 사진이 보여집니다.
프로필 사진이 null 이라도 정상적으로 조회 가능합니다.
closes #192
=> 회원가입 시 프로필 사진 선택 기능 구현 완료

src/main/java/balancetalk/module/post/application/PostService.java, src/main/java/balancetalk/module/post/dto/PostResponse.java
프론트엔드에서 요청하여 게시글 응답 DTO에 투표 여부를 추가했습니다.
회원이 조회한 경우에만 동작하며, 투표한 이력이 있는 게시글일 경우 true를 반환합니다.
closes #197
=> 게시글 응답 DTO에 투표 여부 추가

src/main/java/balancetalk/global/config/SecurityConfig.java, src/main/java/balancetalk/module/comment/application/CommentService.java, src/main/java/balancetalk/module/comment/domain/CommentLike.java, src/main/java/balancetalk/module/comment/domain/CommentRepository.java, src/main/java/balancetalk/module/comment/dto/CommentResponse.java, src/main/java/balancetalk/module/comment/presentation/CommentController.java, src/main/java/balancetalk/module/member/domain/Member.java, src/main/java/balancetalk/module/member/domain/MemberRepository.java
- 추천 수 15개 이상
- 하나의 게시글 안에 있는 2개의 선택지별로 최대 3개
하나의 게시글 안에 있는 2개의 선택지별로 추천 수가 15개 이상인 댓글을 최대 3개 조회하도록 구현했습니다.
테이블 간의 관계를 보면 댓글과 선택지가 간접적으로 연결되어 있긴 하지만 멀리 떨어져 있습니다.
단순히 쿼리 메서드를 이용해서 구현하기에는 한계가 보여서 직접 작성하는 방식을 택했습니다.
쿼리를 어떻게 작성해야 할지 고민한 결과, 서브 쿼리를 이용하기로 했으며 전체 쿼리를 작성한 부분은 다음과 같습니다.
```sql
select c.* from comment as c left join comment_like as l using(comment_id) 
where c.post_id = 14 and c.member_id in (
select m.member_id from vote as v join member as m using(member_id) where v.balance_option_id = 27)
group by c.comment_id having count(l.comment_like_id) >= 2
order by count(l.comment_like_id) desc;
```
먼저 LEFT JOIN을 통해 COMMENT 테이블과 COMMENT_LIKE 테이블을 연결합니다.
그러면 아래와 같이 테이블이 나옵니다.
여기서 우리가 궁금한 것은 특정 ID의 게시글에 작성된 댓글이므로 `c.post_id = {post_id}`라는 조건식을 사용합니다.
그리고 해당 댓글의 작성자 ID가 특정 선택지에 투표한 회원의 ID들 중 …
=> 인기 댓글 조회 기능 구현

src/main/java/balancetalk/module/post/application/PostService.java, src/main/java/balancetalk/module/post/domain/PostRepository.java, src/main/java/balancetalk/module/post/presentation/PostController.java
작성일 기준 월간 추천 수가 높은 게시글 순으로 상위 최대 5개를 조회하도록 했습니다.
만약 추천 수가 동일하다면 조회수가 더 높은 게시글 순으로 조회합니다.
```java
@Query("select p "
+ "from Post p left join p.likes l "
+ "where p.deadline > current_timestamp "
+ "and function('month', p.createdAt) = function('month', current_timestamp) "
+ "group by p.id "
+ "order by count(l) desc, p.views desc")
List<Post> findBestPosts(Pageable pageable);
```
메서드 이름으로 조회하기에는 쿼리가 복잡해서 쿼리를 직접 작성하는 방식으로 구현했습니다.
closes #이슈번호
=> 인기 게시글 조회 기능 구현

src/main/java/balancetalk/module/post/dto/BalanceOptionDto.java
##![image](https://github.com/CHZZK-Study/Balance-Talk-Backend/assets/73704053/f3ea4519-8875-46b3-840e-5435324e0a9f)
게시글 작성 또는 조회 시 응답에서 balanceOptionId 반환 확인 완료했습니다.
응답 시 기존에 존재하던 id(게시글 id) 필드와의 구분을 위해 balanceOptionId 로 네이밍했습니다.
closes #194
=> 게시글 조회 시 balanceOptionId를 응답하도록 구현 완료

src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/module/file/domain/File.java, src/main/java/balancetalk/module/file/domain/FileRepository.java, src/main/java/balancetalk/module/notice/application/NoticeService.java, src/main/java/balancetalk/module/notice/domain/Notice.java, src/main/java/balancetalk/module/notice/dto/NoticeRequest.java, src/main/java/balancetalk/module/notice/dto/NoticeResponse.java, src/main/java/balancetalk/module/notice/presentation/NoticeController.java, src/test/java/balancetalk/module/notice/application/NoticeServiceTest.java, src/test/java/balancetalk/module/notice/presentation/NoticeControllerTest.java
공지사항 수정 또는 삭제 시 해당 공지사항을 작성하지 않아도 'ADMIN' 이라면 수정 또는 삭제 가능하게 구현했습니다.
파일을 가져오는 로직에서 setNotice로 File 객체에 직접 Notice 객체를 할당 해줬습니다.
추후 파일 업로드 API의 개선이 필요합니다.
1. 공지 사항 조회수 증가 로직 구현
closes #183 #187 #188
=> 공지사항 수정, 삭제 기능, 파일 첨부 구현 완료

src/main/java/balancetalk/module/file/application/FileService.java, src/main/java/balancetalk/module/file/domain/File.java, src/main/java/balancetalk/module/file/presentation/FileController.java, src/main/java/balancetalk/module/post/application/PostService.java, src/main/java/balancetalk/module/post/dto/BalanceOptionRequest.java, src/main/java/balancetalk/module/post/dto/BalanceOptionResponse.java, src/main/java/balancetalk/module/post/dto/PostRequest.java, src/main/java/balancetalk/module/post/dto/PostResponse.java, src/test/java/balancetalk/module/post/application/PostServiceTest.java
게시글을 작성할 때는 BalanceOption에 이미지 이름을 전달하고, 게시글을 응답으로 보낼 때는 이미지의 URL을 보내면 클라이언트 입장에서 효율적인 작업이 가능해집니다.
이를 가능하도록 하려면 기존 BalanceOptionDto를 요청과 응답 각각의 DTO로 분리해야 한다고 판단했습니다.
따라서 BalanceOptionRequest에는 storedImageName을, BalanceOptionResponse에는 imageUrl을 필드로 설정했습니다.
closes #208
=> 게시글 응답 필드(이미지 url) 변경

src/main/java/balancetalk/module/post/dto/BalanceOptionDto.java, src/main/java/balancetalk/module/post/dto/PostResponse.java
선택지별 득표 수 반환 Postman 테스트 완료
게시글 전체 투표 수 반환 Postman 테스트 완료
closes #216
=> 게시글 응답에 선택지별 득표 수, 게시글 전체 투표 수 반환 구현

src/main/java/balancetalk/module/vote/application/VoteService.java, src/main/java/balancetalk/module/vote/dto/VoteRequest.java, src/main/java/balancetalk/module/vote/presentation/VoteController.java, src/test/java/balancetalk/module/vote/application/VoteServiceTest.java
기존에는 boolean 타입인 isUser를 통해 투표를 하는 주체가 회원인지 비회원인지 구분했습니다.
이를 JWT 토큰을 사용해 구분하도록 로직을 개선하였습니다.
closes #213
=> 투표 생성 시 회원/비회원 구분 로직 개선

src/main/java/balancetalk/module/comment/application/CommentService.java, src/main/java/balancetalk/module/comment/domain/CommentRepository.java
쿼리 메서드에서 제공하는 기능을 사용해 댓글 목록 조회 API 응답에서 답글을 제외시켰습니다.
closes #245
=> 댓글 목록 조회 시 답글 제외

src/main/java/balancetalk/module/post/dto/PostResponse.java
`vote.getMember() 또는 vote.getMember().getId() 반환값이 NULL일 경우를 스트림으로 처리해서 해결했습니다.
dev 기준 정상 작동 확인했습니다.
closes #262
=> 로그인 후 게시글 조회 시 에러 발생 해결

src/main/java/balancetalk/global/config/SecurityConfig.java, src/main/java/balancetalk/module/authmail/presentation/MailController.java, src/main/java/balancetalk/module/member/presentation/MemberController.java
세가지 api (회원 닉네임 수정, 비밀번호 수정, 이미지 수정)에 대해서 헤더 타입을 `application/json` 에서 `plain/text` 으로 변경하였습니다.
그리고, 임시 비밀번호 발송 로직이 GET으로 되어 있어서 `401 Unauthorized` 에러가 발생했는데, `POST`로 변경하고 시큐리티 URL까지 허용해줬습니다.
closes #265
=> 스웨거 문서 수정 및 시큐리티 URL 허용

src/main/java/balancetalk/global/config/SecurityConfig.java, src/main/java/balancetalk/module/member/dto/MemberResponse.java, src/main/java/balancetalk/module/vote/dto/VoteRequest.java
기존 회원 조회 시 응답에는 프로필 사진의 storedName이 포함되어 있었습니다. 이를 이미지의 전체 URL이 반환되도록 수정하였습니다.
closes #266
=> 회원 조회 시 응답에 있는 프로필 사진의 storedName을 url로 수정

src/main/java/balancetalk/module/post/domain/Post.java, src/main/java/balancetalk/module/post/dto/PostResponse.java
PostResponse 클래스에 commentsCount라는 필드를 추가했습니다.
commentsCount는 post 엔티티의 comments의 size를 통해 도출했습니다.
closes #270
=> 게시글 조회 응답에 댓글 개수 추가

src/main/java/balancetalk/global/jwt/JwtAuthenticationFilter.java, src/main/java/balancetalk/module/post/domain/PostRepository.java
기존에 태그 검색 쿼리를 Natural Join을 사용해서 구현했으나, 비 로그인시 401에러, 로그인 시 500 에러가 발생하여 INNER JOIN으로 
로직을 변경해서 해결했습니다.
closes #285
=> 태그 검색 시 401 에러가 뜨던 오류 해결 

src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/module/post/application/PostService.java
이유는 잘 모르겠으나 좋아요 해제 로직에서 `likesCount`를 실행시키기만 해도 delete 쿼리가 나가지 않았습니다.
해당 변수를 없애주니 정상적으로 delete 쿼리가 나갔습니다.
closes #291
=> 게시글 좋아요 해제 로직 수정

src/main/java/balancetalk/global/config/RedisConfig.java
기존에 Redis에 Key값으로 룬문자가 붙은 형태로 저장되는 문제가 있었습니다.
수정 후, 정상적으로 key 값이 저장되는 것을 확인할 수 있습니다.
closes #284
=> Redis에 저장되는 값을 직렬화 하는 빈 추가

src/main/java/balancetalk/module/post/application/PostService.java
게시글 조회 시 조회수가 증가하지 않는 문제의 원인을 파악한 결과, 다음과 같이 @Transactional 옵션에 readOnly=true가 설정되어 있음을 확인했습니다.
```java
@Transactional(readOnly = true)
public PostResponse findById(Long postId, String token) {
...
}
```
이로 인해 데이터 수정 작업이 수행되지 않았고, readOnly 설정을 해제함으로써 문제를 해결했습니다.
closes #288
=> 게시글 조회 시 조회수가 증가하지 않던 문제 해결

src/main/java/balancetalk/module/comment/domain/Comment.java, src/main/java/balancetalk/module/comment/dto/CommentResponse.java
postman 테스트 완료했습니다.
closes #286
=> 댓글 목록 조회 API에서 댓글마다 답글 개수 포함하도록 수정 완료

src/main/java/balancetalk/module/member/dto/ProfileResponse.java, src/main/java/balancetalk/module/member/presentation/MemberController.java
회원 프로필이 없는 경우, `null`값을 잡지 못해서 에러가 발생했습니다.
위 코드를 추가했습니다.
프로필이 있는 경우, 없는 경우 둘다 정상적으로 비회원 상태에서 반환되는 것을 확인했습니다.
closes #305
=> 비회원 상태에서 프로필 조회 시 401에러

src/main/java/balancetalk/module/post/domain/Post.java
마감 시간이 지난 게시글 조회 시 `{"message":"must be a future date"}`와 같은 에러가 발생헀습니다.
이유를 찾아보니, 게시글 조회를 할 때 조회수를 올려주기 위해서 update 쿼리도 같이 실행되는데, 그 때 게시글의 작성일자도 새로 업데이트 되기 떄문에 발생한 문제 였습니다.
Post의 deadline attribute에서 `@Future` 어노테이션을 삭제하니, 조회할 때 더 이상 에러가 발생하지 않았습니다.
closes #309
=> 마감시간 지난 게시글 조회 시 에러 발생

src/main/java/balancetalk/module/comment/application/CommentService.java, src/main/java/balancetalk/module/post/application/PostService.java, src/main/java/balancetalk/module/post/domain/Post.java, src/main/java/balancetalk/module/report/domain/ReportRepository.java
`ReportRepository`에서 `existsByReporter`로 쿼리를 작성하여 해당 사용자가 한번이라도 신고를 한 경우 중복되었다는 에러 메세지를 리턴하는 문제가 있었습니다.
`existsByReporterAndPost`, `existsByReporterAndComment`로 수정해 주었습니다.
closes #306
=> 본인 게시글, 댓글을 신고할 때 에러 메세지 수정 및 데드라인 지난 게시글 조회 시 에러

src/main/java/balancetalk/module/comment/dto/ReplyResponse.java
기존 답글 목록 조회 시 작성자 ID가 누락되었습니다.
따라서 답글 목록 조회 API 응답에 작성자 ID를 추가했습니다.
closes #310
=> 답글 목록 조회 응답에 작성자 ID 추가

src/main/java/balancetalk/module/post/domain/Post.java, src/main/java/balancetalk/module/post/dto/PostResponse.java
프론트엔드 요청으로 게시글 조회 시 마감 여부 필드를 추가했습니다.
closes #314
=> 게시글 응답 DTO에 마감 여부 필드 추가

src/main/java/balancetalk/module/post/application/PostService.java, src/main/java/balancetalk/module/post/domain/Post.java, src/main/java/balancetalk/module/post/domain/PostRepository.java, src/main/java/balancetalk/module/post/dto/PostResponse.java, src/main/java/balancetalk/module/post/presentation/PostController.java, src/test/java/balancetalk/module/post/application/PostServiceTest.java
```java
@Transactional(readOnly = true)
public Page<PostResponse> findAll(String token, Boolean containsClosed, Pageable pageable) {
Page<Post> posts = getPosts(containsClosed, pageable);
// 기존 로직과 동일
}
// 마감 여부에 따른 분기 처리
private Page<Post> getPosts(Boolean containsClosed, Pageable pageable) {
if (containsClosed) {
return postRepository.findAll(pageable);
}
return postRepository.findAllOnlyOpened(pageable);
}
```
```java
@Query("select p from Post p where p.deadline > function('now')")
Page<Post> findAllOnlyOpened(Pageable pageable);
```
closes #319
=> 게시글 조회 시 마감 여부 필터링 로직 추가

src/main/java/balancetalk/comment/application/CommentService.java, src/main/java/balancetalk/comment/dto/CommentDto.java, src/main/java/balancetalk/comment/presentation/CommentController.java, src/main/java/balancetalk/like/presentation/LikeController.java
위 명시한 사항들 업데이트 완료했습니다.
다만 #363 에러 이슈 발생했습니다.
#363 에러 해결
closes #360
=> API 명세 수정(댓글, 댓글 좋아요) 완료

src/main/java/balancetalk/comment/presentation/CommentController.java, src/main/java/balancetalk/like/application/CommentLikeService.java, src/main/java/balancetalk/like/domain/Like.java, src/main/java/balancetalk/like/domain/LikeRepository.java, src/main/java/balancetalk/like/dto/LikeDto.java, src/main/java/balancetalk/like/presentation/LikeController.java
`LikeDto` 의 `Request` 에서 메서드 오버로딩을 이용해 `toEntity` 메서드를 2개 작성했습니다.
매개변수로 받는 값이 `Comment` 인지 `TalkPick` 인지에 따라 다른 `LikeType`을 가지는 `Like` 객체를 반환합니다.
또한 CommentLikeService 클래스를 작성했습니다.
1. `CommentLikeService`, `TalkPickLikeService` 두 개로 분할해야 할까요, 아니면 `LikeService` 하나로 통합해야 할까요?
2. 좋아요 취소 시 Like 객체를 삭제하지 않고, deActive() 메서드로 객체를 그대로 유지하면서 `boolean active` 값만 변경하는 게 좋은 방법일까요? 
3. unlikeComment 메서드에 사용된 `@DeleteMapping` 이 적절할까요?
1. 댓글 정렬 기능 구현
2. 메서드 분리
3. 예외 처리
closes #366
=> 댓글 좋아요, 좋아요 취소 구현 완료

src/main/java/balancetalk/comment/application/CommentService.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/global/exception/GlobalExceptionHandler.java, src/main/java/balancetalk/like/application/CommentLikeService.java, src/main/java/balancetalk/like/domain/LikeRepository.java, src/main/java/balancetalk/like/dto/LikeDto.java, src/main/java/balancetalk/like/presentation/LikeController.java
1. 멤버 존재 여부
2. 해당 톡픽 존재 여부
3. 해당 댓글 존재 여부
4. 이미 좋아요 상태인지
1. 멤버 존재 여부
2. 해당 톡픽 존재 여부
3. 해당 댓글 존재 여부
4. 이미 좋아요 취소 상태인지
- `Like` 객체 미생성인 경우
- `Like` 객체는 존재하나, `active` 필드가 false인 경우 
컨트롤러에서 더 이상 추가적인 응답을 필요로 하지 않으므로, 메서드들을 void 타입으로 바꿨습니다.  따라서 응답 Dto도 사용하지 않으므로, 해당 Schema 설명을 변경했습니다.
핸들러 메서드의 반환 타입을 동적인 `ResponseEntity` 로 바꿔줌으로서 해결됐습니다.
closes #375
=> 댓글 좋아요 기능 예외 처리 완료

build.gradle, src/main/java/balancetalk/comment/application/CommentService.java, src/main/java/balancetalk/global/config/QuerydslConfig.java, src/main/java/balancetalk/like/application/CommentLikeService.java, src/main/java/balancetalk/talkpick/application/TodayTalkPickService.java, src/main/java/balancetalk/talkpick/domain/TalkPickRepository.java, src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java, src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryCustom.java, src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java, src/main/java/balancetalk/talkpick/dto/TodayTalkPickDto.java, src/main/java/balancetalk/talkpick/presentation/TodayTalkPickController.java
QueryDSL을 사용하기 위해 의존성 추가 및 설정 클래스를 작성했습니다.
현재 요구사항에 따르면, 투표수가 가장 많으면서 최근에 생성된 톡픽이 오늘의 톡픽으로 선정됩니다.
따라서 오늘의 톡픽을 따로 선정하는 과정 없이, 그룹과 정렬을 통해 조회하도록 구현했습니다.
QueryDSL을 이용해 기능을 구현했으며, 다음과 같이 실제 쿼리가 잘 생성되는 것을 확인했습니다.
closes #371
=> 오늘의 톡픽 조회 기능 구현

src/main/java/balancetalk/comment/application/CommentService.java, src/main/java/balancetalk/comment/dto/CommentDto.java, src/main/java/balancetalk/comment/presentation/CommentController.java, src/main/java/balancetalk/global/exception/ErrorCode.java
메서드 오버로딩으로 댓글 작성의 경우와 답글 작성의 경우를 분리했습니다.
그리고 다음 예외 처리들을 구현했습니다.
1. 멤버 존재 여부
2. 해당 톡픽 존재 여부
3. 부모 댓글 존재 여부
4. 해당 톡픽에 해당 부모 댓글이 존재하는지 여부
5. 부모 댓글의 depth가 maxDepth를 초과하는 경우(답글에 답글 불가)
**혹시 놓친 예외가 있을까요?**
closes #377
=> 답글 작성 기능 구현 및 예외 처리 완료

src/main/java/balancetalk/comment/application/CommentService.java, src/main/java/balancetalk/comment/domain/Comment.java, src/main/java/balancetalk/comment/dto/CommentDto.java, src/main/java/balancetalk/comment/presentation/CommentController.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/global/exception/GlobalExceptionHandler.java, src/main/java/balancetalk/vote/domain/VoteOption.java
위 사진처럼 제약 조건 예외 발생 시, 올바른 상태 코드가 반환되지 않음을 확인했습니다.
`ConstraintViolationException` 발생 시에도 ResponseEntity를 반환하게 함으로써 올바른 상태 코드를 반환하도록 했습니다.
댓글, 답글 작성 시 RequestBody로 받는 `option` 값이 `VoteOption` 에 존재하지 않는 값일 때의 예외를 처리하던 중, 역직렬화 문제가 발생했습니다.
``` 
DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `balancetalk.vot....
```
이를 처리하기 위해 `VoteOption`에 `@JsonCreator`로 역직렬화 문제를 해결했습니다. postman 테스트 결과 정상적으로 예외 처리 및 상태 코드 반환이 이뤄집니다.
사용하지 않는 주석 코드, 필드 등을 제거했습니다.
혹시 빠트린 예외 처리가 있을까요?
closes #378
=> 댓글 예외 처리 및 Code CleanUp 완료

src/main/java/balancetalk/comment/application/CommentService.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/like/application/CommentLikeService.java, src/main/java/balancetalk/like/presentation/LikeController.java
URI를 기존의 `/{talkPickId}/{commentId}/likes` 에서 `/{talkPickId}/comments/{commentId}/likes` 로 더 직관적으로 변경했습니다.
1. talkPickId와 CommentId 의 일치 여부
2. 본인 댓글 좋아요 불가
3. 좋아요를 누르지 않은 댓글에 좋아요 취소를 누를 경우
의 예외 처리를 추가했습니다.
놓친 예외 처리가 있을까요?
closes #379
=> 댓글 좋아요/좋아요 취소 URI 수정 및 추가 예외 처리 완료

src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
기존 오늘의 톡픽 조회 기준은 '투표수 > 생성일'이었지만, 요구사항 변경으로 인해 기준이 다음과 같이 변경되었습니다.
'조회수 > 투표수 > 생성일'
따라서 기존에 구현한 오늘의 톡픽 조회 기능 중 정렬 부분을 수정하였습니다.
closes #406
=> 변경된 요구사항에 따라 오늘의 톡픽 조회 로직 수정

src/main/java/balancetalk/comment/application/CommentService.java, src/main/java/balancetalk/comment/presentation/CommentController.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/like/application/CommentLikeService.java, src/main/java/balancetalk/like/domain/Like.java, src/main/java/balancetalk/like/presentation/LikeController.java
```java
@Transactional
public void createCommentReply(CommentDto.CreateCommentRequest createCommentRequest, Long talkPickId, Long commentId,
ApiMember apiMember) {
Member member = apiMember.toMember(memberRepository);
TalkPick talkPick = validateTalkPickId(talkPickId);
Comment parentComment = validateCommentId(commentId);
// 부모 댓글과 연결된 게시글이 아닌 경우 예외 처리
if (!parentComment.getTalkPick().equals(talkPick)) {
throw new BalanceTalkException(NOT_FOUND_PARENT_COMMENT_AT_THAT_TALK_PICK);
}
// 부모 댓글의 depth가 maxDepth를 초과하는 경우 예외 처리 (답글에 답글 불가)
validateDepth(parentComment);
Comment commentReply = createCommentRequest.toEntity(member, talkPick, parentComment);
commentRepository.save(commentReply);
}
```
댓글, 댓글 좋아요 기능에서 `ApiMember` 와 `GuestOrApiMember` 클래스를 사용하여 위와 같이 현재 로그인한 멤버 조회 로직을 변경했습니다.
댓글 좋아요 …
=> 회원 로직 변경에 따른 기존 댓글, 댓글 좋아요 코드 수정 및 추가 기능 구현

build.gradle, src/main/java/balancetalk/global/config/SwaggerConfig.java, src/main/java/balancetalk/member/domain/Member.java, src/main/java/balancetalk/talkpick/presentation/TalkPickController.java, src/main/java/balancetalk/vote/application/VoteTalkPickService.java, src/main/java/balancetalk/vote/domain/Vote.java, src/main/java/balancetalk/vote/domain/VoteType.java, src/main/java/balancetalk/vote/dto/VoteGameDto.java, src/main/java/balancetalk/vote/dto/VoteTalkPickDto.java, src/main/java/balancetalk/vote/presentation/VoteGameController.java, src/main/java/balancetalk/vote/presentation/VoteTalkPickController.java
인증을 위해 사용하는 GuestOrApiMember와 ApiMember가 Swagger UI에 포함되는 문제를 발견했습니다.
따라서 이를 `@Parameter(hidden = true)`로 해결하였습니다.
Swagger 3.0 기준 `@Parameter(hidden = true)` 어노테이션을 이용해 특정 파라미터를 Swagger UI에서 숨길 수 있습니다. 
다만, 모든 파라미터에 해당 어노테이션을 붙여야 한다는 번거로움이 생긴다는 단점이 존재합니다.
따라서 더 좋은 방법을 찾게 된다면 수정할 예정입니다.
closes #421
=> 톡픽 투표 기능 구현

src/main/java/balancetalk/talkpick/domain/TalkPick.java, src/main/java/balancetalk/talkpick/dto/TalkPickDto.java, src/main/java/balancetalk/talkpick/dto/TodayTalkPickDto.java, src/main/java/balancetalk/vote/domain/Vote.java, src/main/java/balancetalk/vote/presentation/VoteTalkPickController.java, src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
톡픽 상세 조회 API 응답에 각 선택지에 대한 투표수 필드를 추가했습니다.
closes #423
=> 톡픽 상세 조회 API 응답에 각 선택지에 대한 투표수 필드 추가

src/main/java/balancetalk/game/application/GameService.java, src/main/java/balancetalk/game/domain/repository/GameRepository.java, src/main/java/balancetalk/game/presentation/GameController.java
인기순으로 정렬하는 기능은 초기 단계에서는 좋아요 갯수가 아닌 조회수로 정렬해서 보여주도록 구현했습니다.
closes #432
=> 밸런스 게임 최신순, 인기순 조회 로직 구현

src/main/java/balancetalk/file/domain/FileRepository.java, src/main/java/balancetalk/game/application/GameService.java, src/main/java/balancetalk/game/domain/Game.java, src/main/java/balancetalk/game/dto/GameDto.java
이미지 파일을 업로드 할 때 리스트 형태로 File DB에서 조회를 합니다.
만약에 조회를 했을 때 리스트의 사이즈가 2보다 작다면, 둘 중 하나 혹은 두개의 이미지 이름이 DB에 존재하지 않는다는 뜻 이므로 에러를 던져 줍니다.
closes #434
=> 밸런스 게임 이미지 등록 구현

src/main/java/balancetalk/global/jwt/ApiMemberArgumentResolver.java, src/main/java/balancetalk/global/jwt/JwtTokenProvider.java, src/main/java/balancetalk/global/oauth2/CustomSuccessHandler.java, src/main/java/balancetalk/global/oauth2/service/CustomOAuth2UserService.java, src/main/java/balancetalk/member/application/MyUserDetailService.java, src/main/java/balancetalk/member/dto/ApiMember.java
계속해서 어디 로직은 회원 조회를 할 때 `email`로 하고, 어디는 `memberId`로 하니 통일성이 없고, 에러가 발생해도 디버깅하는데 오래걸렸습니다.
그래서, `memberId`를 통해서 조회하는 것으로 통일했습니다. 
closes #438
=> 회원 조회 방식을 email이 아닌 id로 변경

src/main/java/balancetalk/file/domain/FileRepository.java, src/main/java/balancetalk/game/application/GameService.java, src/main/java/balancetalk/member/application/MemberService.java, src/main/java/balancetalk/member/domain/Member.java, src/main/java/balancetalk/member/dto/MemberDto.java, src/main/java/balancetalk/member/presentation/MemberController.java
기존에 밸런스 게임을 생성할 때 File DB를 조회 한 후  `storedName`을 보내주는 식으로 구현을 했었는데 이미지 파일을 보내주도록 변경했습니다.
closes #440
=> 회원 이미지 관련 작업

build.gradle, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/global/notification/application/NotificationService.java, src/main/java/balancetalk/global/notification/domain/Notification.java, src/main/java/balancetalk/global/notification/domain/NotificationRepository.java, src/main/java/balancetalk/global/notification/presentation/NotificationController.java
SSE(Server-Sent Events) 를 적용한 실시간 알림 기능을 구현했습니다. SSE는 간단히 말하자면, 서버에서 특정 이벤트가 일어나면 연결이 맺어져 있는 동안 클라이언트에게 실시간으로 동작을 전송해줍니다.
[출처](https://stonehee99.tistory.com/30)
원래는 웹소켓을 이용하여 구현하려 했으나, 알림 기능은 서버->클라이언트 단방향 통신이고, 구현의 간단함으로 인해 SSE 방식을 채택했습니다.
```java
public SseEmitter createEmitter(ApiMember apiMember) {
Long memberId = apiMember.toMember(memberRepository).getId();
SseEmitter emitter = new SseEmitter(Long.MAX_VALUE);
memberEmitters.put(memberId, emitter);
// 연결 종료 / 만료 / 에러 발생 시 emitter 제거
emitter.onCompletion(() -> memberEmitters.remove(memberId, emitter));
emitter.onTimeout(() -> memberEmitters.remove(memberId, emitter));
emitter.onError((e) -> memberEmitters.remove(memberId, emitter));
return emitter;
}
```
`SseEmitter` : Spring에서 제공하는 클래스로, 서버가 클라이언트에 실시간 데이터를 전송할 수 있게 합니다. …
=> SSE 적용 실시간 알림 기능 구현

src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
URL에 페이징 관련 파라미터 지정하지 않을 경우, 기본적으로 다음과 같은 페이징 옵션이 추가됩니다.
- 페이지 내 데이터 개수: 20
- 정렬 기준: 톡픽 생성일
- 정렬 방식: 내림차순
closes #464
=> 톡픽 목록 조회 기능에 페이징 기본 옵션 추가

src/main/java/balancetalk/talkpick/application/TalkPickService.java, src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryCustom.java, src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java, src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
```java
@Override
public List<TalkPickResponse> findBestTalkPicks() {
return queryFactory
.select(new QTalkPickDto_TalkPickResponse(
talkPick.id, talkPick.title, talkPick.member.nickname,
talkPick.createdAt, talkPick.views, talkPick.bookmarks
))
.from(talkPick)
.orderBy(talkPick.views.desc(), talkPick.createdAt.desc())
.limit(3)
.fetch();
}
```
```sql
select * from talk_pick 
order by views desc, created_at desc 
limit 3;
```
closes #466
=> 인기 톡픽 조회 기능 구현

src/main/java/balancetalk/bookmark/application/BookmarkTalkPickService.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/member/domain/Member.java, src/test/java/balancetalk/bookmark/application/BookmarkTalkPickServiceTest.java
이미 북마크한 톡픽에 더 이상 북마크할 수 없다는 예외 처리 로직을 추가했습니다.
closes #477
=> 이미 북마크한 톡픽에 더 이상 북마크할 수 없다는 예외 처리 추가

src/main/java/balancetalk/talkpick/dto/TalkPickDto.java, src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
=> 톡픽 상세조회 API의 응답 중 수정일을 lastModifiedAt이 아닌 editedAt으로 변경

src/main/java/balancetalk/talkpick/domain/TalkPick.java, src/main/java/balancetalk/talkpick/dto/TalkPickDto.java, src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
변경된 요구사항에 따라 톡픽 상세 조회 API의 응답에서 수정일을 생성일로 변경했습니다.
그리고 톡픽 편집 여부 판단 로직을 다음과 같이 변경했습니다.
```java
public boolean isEdited() {
return editedAt != null;
}
```
closes #492
=> 톡픽 상세 조회 API의 응답에서 수정일을 생성일로 변경

src/main/java/balancetalk/file/application/FileService.java, src/main/java/balancetalk/file/domain/File.java, src/main/java/balancetalk/file/domain/FileProcessor.java, src/main/java/balancetalk/file/domain/FileType.java, src/main/java/balancetalk/file/domain/MultipartFiles.java, src/main/java/balancetalk/file/dto/UploadFileResponse.java, src/main/java/balancetalk/file/presentation/FileController.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/test/java/balancetalk/file/domain/FileProcessorTest.java
```java
public UploadFileResponse uploadImage(@RequestPart("file") List<MultipartFile> multipartFiles,
@Parameter(description = "리소스 타입", example = "TALK_PICK") @RequestParam("type") FileType fileType) {
return fileService.uploadImages(new MultipartFiles(multipartFiles, fileType));
...
```
```java
public record MultipartFiles(List<MultipartFile> multipartFiles, FileType fileType) {
public MultipartFiles {
if (multipartFiles == null || containsEmptyFile(multipartFiles)) {
throw new BalanceTalkException(NOT_ATTACH_IMAGE);
}
if (multipartFiles.size() > fileType.getMaxCount()) {
throw new BalanceTalkException(EXCEEDED_IMAGES_SIZE);
}
}
private boolean containsEmptyFile(List<MultipartFile> multipartFiles) {
return multipartFiles.stream().anyMatch(MultipartFile::isEmpty);
}
...
```
기존에는 파일 관련 …
=> 이미지 업로드 기능 개선

src/main/java/balancetalk/comment/domain/Comment.java, src/main/java/balancetalk/comment/domain/CommentRepository.java, src/main/java/balancetalk/comment/dto/CommentDto.java, src/main/java/balancetalk/game/domain/Game.java, src/main/java/balancetalk/game/domain/repository/GameRepository.java, src/main/java/balancetalk/game/dto/GameDto.java, src/main/java/balancetalk/global/notification/presentation/NotificationController.java, src/main/java/balancetalk/member/application/MyPageService.java, src/main/java/balancetalk/member/presentation/MyPageController.java, src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java, src/main/java/balancetalk/talkpick/dto/TalkPickDto.java, src/main/java/balancetalk/vote/domain/VoteRepository.java
톡픽 생성 시에 `editedAt` 값을 정해주지 않으면, 마이페이지에서 톡픽 조회 시 `editedAt` 기준으로 내림차순이 불가하기 때문에, `TalkPickDto` 에서 톡픽 생성 요청 시 초기값을 설정하도록 구현했습니다.
'내가 작성한 톡픽 조회' 와 마찬가지로, 본인의 댓글에 답글이 달리거나, 좋아요를 받는 상황에서도 `lastModifiedAt` 값이 변경 되기 때문에, 이를 구분하기 위한 `editedAt` 필드를 추가하고, 이 값을 기준으로 댓글 단 톡픽을 조회하도록 구현했습니다.
1. 톡픽 이미지 업로드 기능 구현 완료 후, 마이페이지에서 톡픽 조회 시 선택지 이미지 반환
2. 밸런스 게임 기능 명세서 & 피그마가 미완인 상태라, 마이페이지에서 밸런스 게임 조회 시 어떤 값을 클라이언트에 전달해줘야 하는지 불분명한 상황. 추후 기능 명세서 업데이트 시 추가 구현 예정
closes #490 #491
=> 마이페이지 - 밸런스 게임 조회 기능 구현 및 톡픽 조회 일부 기능 수정

src/main/java/balancetalk/file/application/FileService.java, src/main/java/balancetalk/file/domain/FileRepository.java, src/main/java/balancetalk/file/domain/repository/FileRepository.java, src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java, src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java, src/main/java/balancetalk/file/dto/UploadFileResponse.java, src/main/java/balancetalk/talkpick/application/TalkPickService.java, src/main/java/balancetalk/talkpick/domain/TalkPick.java, src/main/java/balancetalk/talkpick/dto/TalkPickDto.java, src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
톡픽 작성/수정 API 요청 바디에 출처와 이미지 정보를 담아서 전달하도록 개선했습니다.
closes #506
=> [톡픽 작성&수정] 요청 바디에 타 웹사이트 출처와 이미지 URL 배열 추가

src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java, src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java, src/main/java/balancetalk/talkpick/application/TalkPickService.java, src/main/java/balancetalk/talkpick/dto/TalkPickDto.java, src/test/java/balancetalk/talkpick/application/TalkPickServiceTest.java
톡픽 상세 조회 API 응답에 이미지 URL 목록을 추가했습니다.
closes #512
=> 톡픽 상세 조회 API 응답에 이미지 URL 추가

src/main/java/balancetalk/file/domain/repository/FileRepositoryCustom.java, src/main/java/balancetalk/file/domain/repository/FileRepositoryImpl.java, src/main/java/balancetalk/talkpick/application/TalkPickService.java, src/main/java/balancetalk/talkpick/application/TempTalkPickService.java
임시 저장했던 톡픽을 TalkPick 엔티티로 저장하는 로직에서, 연관된 파일의 타입이 TEMP_TALK_PICK 그대로 남아 있는 문제가 발생했습니다.
이를 해결하기 위해, 이미지 파일 정보 업데이트 로직을 다음과 같이 개선했습니다.
```java
@Override
public void updateResourceIdAndTypeByStoredNames(Long resourceId, FileType fileType, List<String> storedNames) {
if (storedNames == null) {
return;
}
queryFactory.update(file)
.set(List.of(file.resourceId, file.fileType), List.of(resourceId, fileType))
.where(file.storedName.in(storedNames))
.execute();
}
```
closes #이슈번호
=> 임시 저장했던 톡픽 등록 시 파일 타입을 TALK_PICK으로 변경

src/main/java/balancetalk/game/dto/GameDto.java, src/main/java/balancetalk/member/presentation/MyPageController.java, src/main/java/balancetalk/talkpick/dto/TalkPickDto.java
각 DTO에서 편집 날짜를 반환하도록 구현했습니다. 
closes #524
=> 마이페이지 컨텐츠 반환 시 DTO에 마이페이지 등록 날짜 포함 구현 완료

src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java
기존 <<오늘의 톡픽 조회 API>>의 쿼리는 다음과 같이 작성되어 있습니다.
```sql
select t.id, t.title, t.option_a, t.option_b 
from vote v join talk_pick t on v.talk_pick_id = t.id
group by t.id
order by t.views desc, count(v.id) desc, t.created_at desc
limit 1;
```
이 쿼리에서는 inner join을 사용하여, vote 테이블에 데이터가 없으면 어떤 데이터도 조회되지 않는다는 문제가 존재했습니다.
(아래 그림을 보면 더 쉽게 이해할 수 있습니다)
inner join으로 조회할 경우 겹치는 영역에 존재하는 데이터만 가져오기 때문에, vote 데이터가 없으면 어떤 데이터도 존재하지 않는 것입니다.
반면에, left join으로 조회할 경우 talk_pick 전체를 가져오므로, vote 데이터가 없더라도 데이터가 존재하게 됩니다.
closes #531
=> 오늘의 톡픽 조회 쿼리 개선

src/main/java/balancetalk/game/dto/GameDto.java
밸런스게임 구조를 바꾸면서 생성할 때 `bookmarks`, `views`값을 누락해서 값이 null로 들어오게 되어 API 호출 시에 NPE에러가 발생했습니다. 
500 에러는, 연관 관계를 바꾸면서 생긴 오류인데, 기존에 Vote 테이블이 Game을 가르키고 있던 것을 Game_Option으로 연관 관계를 다시 맺어주었습니다.
closes #537
=> 밸런스 게임 생성 시 누락된 북마크, 조회수 값 추가

build.gradle, src/main/java/balancetalk/global/config/OpenaiConfig.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/talkpick/application/SummaryContentService.java, src/main/java/balancetalk/talkpick/domain/Summary.java, src/main/java/balancetalk/talkpick/domain/TalkPick.java, src/main/java/balancetalk/talkpick/dto/SummaryResponse.java, src/main/java/balancetalk/talkpick/dto/TalkPickDto.java, src/main/java/balancetalk/talkpick/presentation/SummaryContentController.java
SpringAI를 통해 OpenAI의 chatGPT4o API를 연결하여, 톡픽 본문 요약 기능을 구현했습니다.
https://spring.io/projects/spring-ai
https://figure.kim/post/spring-ai
현재 구현한 요약 기능의 경우, 어떤 이유로 요약에 실패했을 때 예외만 던집니다.
하지만 요약에 실패했을 때 자동으로 재요청해야 하므로, retry 라이브러리를 이용해 구현할 예정입니다.
시스템 메시지를 하드코딩하여 구현했습니다. 이를 DB에서 관리하도록 개선할 예정입니다.
closes #521
=> 톡픽 본문 요약 기능 구현

src/main/java/balancetalk/bookmark/domain/BookmarkRepository.java, src/main/java/balancetalk/comment/domain/CommentRepository.java, src/main/java/balancetalk/game/domain/repository/GameRepository.java, src/main/java/balancetalk/member/application/MyPageService.java, src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepository.java, src/main/java/balancetalk/vote/domain/TalkPickVoteRepository.java, src/main/java/balancetalk/vote/domain/VoteRepository.java
기존 마이페이지 조회 리포지토리 메서드들이 `List<>` 타입이라서 페이지네이션의 `size`의 `defaultValue(6)` 값이 적용이 안 되는 에러가 발생했었습니다. 리포지토리 메서드들을 `Page<>` 으로 변경해줌으로서 에러를 해결했습니다.
closes #558
=> 마이페이지 페이지네이션 size 적용되지 않는 에러 해결

build.gradle, src/main/java/balancetalk/BalanceTalkApplication.java, src/main/java/balancetalk/talkpick/application/SummaryContentService.java
톡픽 본문 요약 메서드에 `@Retryable` 어노테이션을 추가함으로써, 예외가 발생했을 때 최대 3회까지 재수행되도록 구현했습니다.
https://hvho.github.io/2021-12-05/spring-retry
closes #556
=> 톡픽 본문 요약 기능에 재요청 로직 추가

src/main/java/balancetalk/file/domain/File.java, src/main/java/balancetalk/global/config/MySQLFunctionContributor.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/global/utils/QuerydslUtils.java, src/main/java/balancetalk/talkpick/application/SearchTalkPickService.java, src/main/java/balancetalk/talkpick/domain/repository/SearchTalkPickRepository.java, src/main/java/balancetalk/talkpick/domain/repository/SearchTalkPickRepositoryCustom.java, src/main/java/balancetalk/talkpick/domain/repository/SearchTalkPickRepositoryImpl.java, src/main/java/balancetalk/talkpick/domain/repository/TalkPickRepositoryImpl.java, src/main/java/balancetalk/talkpick/dto/SearchTalkPickResponse.java, src/main/java/balancetalk/talkpick/dto/SummaryResponse.java, src/main/java/balancetalk/talkpick/presentation/SearchTalkPickController.java, src/main/java/balancetalk/talkpick/presentation/SummaryContentController.java, src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
Querydsl에서 MySQL의 사용자 정의 함수를 사용하려면 다음과 같이 FunctionContributor의 구현 클래스를 작성해야 합니다.
```java
public class MySQLFunctionContributor implements FunctionContributor {
@Override
public void contributeFunctions(FunctionContributions functionContributions) {
functionContributions.getFunctionRegistry()
.registerPattern(
"match_talk_pick_in_boolean_mode",
"MATCH(?1, ?2, ?3, ?4, ?5, ?6, ?7) AGAINST(?8 IN BOOLEAN MODE)",
getBooleanBasicType(functionContributions));
functionContributions.getFunctionRegistry()
.registerPattern(
"match_talk_pick_in_natural_mode",
"MATCH(?1, ?2, ?3, ?4, ?5, ?6, ?7) AGAINST(?8)",
getBooleanBasicType(functionContributions));
}
private BasicType<Boolean> getBooleanBasicType(FunctionContributions functionContributions) {
return functionContributions.getTypeConfiguration() …
```
=> 톡픽 검색 기능 구현

src/main/java/balancetalk/bookmark/application/BookmarkGameService.java, src/main/java/balancetalk/game/application/GameService.java, src/main/java/balancetalk/game/domain/Game.java, src/main/java/balancetalk/game/domain/GameSet.java, src/main/java/balancetalk/game/domain/MainTag.java, src/main/java/balancetalk/game/domain/repository/GameRepository.java, src/main/java/balancetalk/game/domain/repository/GameSetRepository.java, src/main/java/balancetalk/game/dto/GameDto.java, src/main/java/balancetalk/game/presentation/GameController.java, src/main/java/balancetalk/global/exception/ErrorCode.java, src/main/java/balancetalk/member/application/MyPageService.java, src/main/java/balancetalk/member/domain/Member.java, src/main/java/balancetalk/vote/application/VoteGameService.java
밸런스 게임 하나 당 2개의 밸런스 게임 옵션을 가지고 있고 밸런스 게임 세트 하나당 10개의 밸런스 게임이 존재합니다.
밸런스 게임 세트가 생성될 때, 성공적으로 `Game_Set` <-> `Game` <-> `Game_Options` 연관 관계를 맺어주었습니다.
밸런스 게임의 수는 무조건 **10개**여야 하기 때문에, 예외 처리를 해주었습니다.
---
북마크 처리를 할 때는, `GameSet`을 스트림 돌려서 주어진 `game_id`와 일치하는 게임이 있다면 해당 게임의 `GameSet`을 가져오고 없다면 예외 처리를 해주도록 리팩토링을 진행했습니다.
closes #589
=> ERD구조 변경에 따라 밸런스 게임 구조 리팩토링

src/main/java/balancetalk/game/application/GameService.java, src/main/java/balancetalk/game/domain/repository/GameSetRepository.java, src/main/java/balancetalk/game/dto/GameSetDto.java, src/main/java/balancetalk/game/presentation/GameController.java
목록 페이지에 id값, 메인 태그, 서브 태그, 제목, 그리고 이미지 파일 두개를 보여주도록 설정했습니다. 목록에 표시되는 값들은 GameSet의 첫번째 Game을 기준으로 조회되도록 구현했습니다.
closes #597
=> 밸런스 게임 목록 최신순, 인기순 기능 리팩토링

src/main/java/balancetalk/comment/application/CommentService.java, src/main/java/balancetalk/comment/domain/Comment.java, src/main/java/balancetalk/comment/domain/CommentRepository.java, src/main/java/balancetalk/comment/dto/CommentDto.java, src/main/java/balancetalk/comment/presentation/CommentController.java
```java
Page<Comment> findAllByTalkPickIdAndParentIsNull(Long talkPickId, Pageable pageable);
@Query("SELECT c FROM Comment c WHERE c.parent.id = :parentId " +
"ORDER BY CASE WHEN c.member.id = :currentMemberId THEN 0 ELSE 1 END, c.createdAt ASC")
Page<Comment> findAllRepliesByParentIdOrderByMemberAndCreatedAt(@Param("parentId") Long parentId,
@Param("currentMemberId") Long currentMemberId,
Pageable pageable);
@Query("SELECT c FROM Comment c LEFT JOIN Like l ON c.id = l.resourceId AND l.likeType = :likeType " +
"WHERE c.talkPick.id = :talkPickId AND c.parent IS NULL " +
"GROUP BY c " +
"ORDER BY COUNT(l) DESC, c.createdAt ASC")
List<Comment> findByTalkPickIdAndParentIsNullOrderByLikesCountDescCreatedAtAsc(@Param("talkPickId") Long talkPickId,
@Param("likeType") LikeType likeType);
```
댓글 …
=> 답글 기능 분리, 댓글 기능 수정 완료

src/main/java/balancetalk/talkpick/application/TalkPickService.java, src/main/java/balancetalk/talkpick/application/TempTalkPickService.java, src/main/java/balancetalk/talkpick/presentation/TalkPickController.java
클라이언트에서 톡픽 요약 API 요청을 하려면, 앞서 생성된 톡픽의 ID를 전달해야 합니다.
따라서 톡픽 생성 API가 생성한 톡픽 ID를 반환하도록 응답을 수정했습니다.
closes #606
=> 톡픽 생성 API 응답을 톡픽 ID로 변경

src/main/java/balancetalk/bookmark/application/BookmarkGameService.java, src/main/java/balancetalk/bookmark/domain/Bookmark.java, src/main/java/balancetalk/bookmark/domain/BookmarkGenerator.java, src/main/java/balancetalk/bookmark/domain/BookmarkRepository.java, src/main/java/balancetalk/bookmark/domain/BookmarkType.java, src/main/java/balancetalk/bookmark/presentation/BookmarkGameController.java, src/main/java/balancetalk/game/application/GameService.java, src/main/java/balancetalk/game/domain/Game.java, src/main/java/balancetalk/game/domain/GameReader.java, src/main/java/balancetalk/game/domain/GameSet.java, src/main/java/balancetalk/game/dto/GameDto.java, src/main/java/balancetalk/game/dto/GameSetDto.java, src/main/java/balancetalk/member/application/MyPageService.java, src/main/java/balancetalk/member/domain/Member.java, src/main/java/balancetalk/vote/application/VoteGameService.java
너무 많은 곳을 수정해서, 밸런스게임 북마크 로직 실행 순서를 따라 설명하겠습니다.
먼저, `createBookmark()` 메서드 입니다.
예외처리 후, 해당 멤버가 해당 GameSet에 대해 북마크가 이미 존재한다면, 해당 `Bookmark` 엔티티가 가지는 `gameId` 필드를 업데이트 합니다. 
만약 북마크가 존재하지 않는다면, 새로 북마크를 생성하고, 이 경우에만 해당 `GameSet` 의 `bookmarks` 수를 증가시킵니다. 
```java
public void createBookmark(final Long gameSetId, Long gameId, final ApiMember apiMember) {
GameSet gameSet = gameReader.findGameSetById(gameSetId);
Member member = apiMember.toMember(memberRepository);
if (member.isMyGameSet(gameSet)) {
throw new BalanceTalkException(ErrorCode.CANNOT_BOOKMARK_MY_RESOURCE);
}
// 밸런스게임 세트, 게임 아이디가 모두 일치한다면 예외 처리
if (member.hasBookmarked(gameSetId, gameId, GAME_SET)) {
throw new BalanceTalkException(ErrorCode.ALREADY_BOOKMARKED);
}
// 해당 멤버가 가진 GameSet 북마크 중, resourceId가 gameSetId와 일치하는 북마크가 있다면 …
```
=> 마이페이지 - 내가 저장한 밸런스게임 기능 수정 및 투표 중도 복귀 기능 구현

.github/workflows/ci.yml, build.gradle
기존 t2.micro 인스턴스에서 실행하던 SonarQube 서버를 다른 인스턴스로 분리했습니다.
이에 따라 관련 설정을 수정하였습니다.
closes #618
=> SonarQube 서버를 분리함으로써, 관련 설정 추가 및 CI 워크 플로우 수정

src/main/java/balancetalk/game/domain/GameSet.java
```java
public long getVotesCount() {
return games.get(0).getVoteCount(VoteOption.A) + games.get(0).getVoteCount(VoteOption.B);
}
```
`GameSet` 엔티티 내에 `getVotesCount()` 메서드를 만들었습니다.
플로우 및 기능상, 밸런스게임 세트에서 투표를 하지 않으면 다음 밸런스게임으로 넘어갈 수 없으므로, 해당 밸런스게임 세트의 **첫 번째 밸런스게임 투표 수 = 밸런스게임 세트 투표 수**와 같습니다. 
closes #612
=> 밸런스게임 세트 투표수 구현 완료

src/main/java/balancetalk/game/dto/GameSetDto.java, src/main/java/balancetalk/global/oauth2/CustomSuccessHandler.java, src/main/java/balancetalk/global/oauth2/dto/CustomOAuth2User.java, src/main/java/balancetalk/global/oauth2/dto/Oauth2Dto.java, src/main/java/balancetalk/global/oauth2/service/CustomOAuth2UserService.java, src/main/java/balancetalk/member/domain/Member.java, src/main/java/balancetalk/member/domain/MemberRepository.java
소셜 로그인으로 가입할 때, provider + "_" + email 형태로 DB에 저장되게끔 구현하여 동일한 값이 DB에 저장되지 않도록 구현했습니다.
기존에 식별자로 쓰이던 username 필드는 email이 unique해짐에 따라서 삭제했습니다.
closes #646
=> 중복된 이메일 오류 해결

src/main/java/balancetalk/talkpick/domain/TalkPick.java
TalkPick 엔티티의 votes 필드에서 CascadeType을 ALL에서 REMOVE로 변경함으로써 delete 문이 정상적으로 생성되었습니다.
- 영속성 전이와 delete 문이 생성되지 않는 문제에 대한 인과관계를 분석
- 이와 동일한 문제가 발생할 수 있는 엔티티가 있는지 확인
closes #650
=> 톡픽 투표 삭제 요청 시 delete 문이 생성되지 않는 오류 해결

src/main/java/balancetalk/comment/application/CommentService.java
```java
// option이 VoteOption에 존재하는 값인지 확인 및 예외 처리
VoteOption option = member.getVoteOnTalkPick(talkPick)
.orElseThrow(() -> new BalanceTalkException(NOT_FOUND_VOTE))
.getVoteOption();
if (option == null || !EnumSet.allOf(VoteOption.class).contains(option)) {
throw new BalanceTalkException(NOT_FOUND_VOTE_OPTION);
}
```
더 이상 사용되지 않는 deprecated된 예외처리 코드를 삭제했습니다.
closes #652
=> 답글 작성 시 해당 톡픽 작성자가 예외처리되는 버그 해결 완료

src/main/java/balancetalk/bookmark/application/BookmarkGameService.java, src/main/java/balancetalk/game/application/GameService.java, src/main/java/balancetalk/game/domain/repository/GameTagRepository.java, src/main/java/balancetalk/game/dto/GameSetDto.java, src/main/java/balancetalk/global/notification/domain/NotificationHistory.java
밸런스게임 북마크는 삭제 시, 엔티티를 삭제하지 않고 `GameBookmark`의 active 필드를 false로 바꿔줍니다.
따라서, 북마크 삭제 API 실행 시 북마크 카운트는 감소하지만, 해당 엔티티는 그대로 남아 있습니다.
북마크를 생성하는 아래 로직에서도, 해당 밸런스게임 세트에 대해서 밸런스게임 북마크가 하나라도 존재한다면, 새로운 북마크 엔티티를 생성하지 않고 active 필드를 true로 바꿔줍니다.
```java
member.getGameBookmarkOf(gameSet)
.ifPresentOrElse(
bookmark -> {
bookmark.activate();
bookmark.setIsEndGameSet(false); // 밸런스게임 세트 종료 표시 해제
bookmark.updateGameId(gameId); //gameId도 업데이트
},
() -> { // resourceId가 gameSetId와 일치하는 북마크가 없다면 새로 생성
gameBookmarkRepository.save(bookmarkGenerator.generate(gameSet, gameId, member));
gameSet.increaseBookmarks();
sendBookmarkGameNotification(gameSet);
});
```
그런데 이 경우, 다시 북마크 카운트를 증가시키는 로직이 부재하기에, 동일 밸런스게임 세트에 대해 새로 북마크를 추가해도 북마크 카운트가 증가하지 않았습니다.
이로 인해, [북마크 추가 -> 북마크 삭제 -> 북마크 추가 -> 북마크 삭제] 시 해당 북마크의 카운트가 -1이 …
=> 밸런스게임 북마크 취소 후 카운트 수 적용하도록 수정, 밸런스게임 세트 조회 시 북마크 관련 로직 수정

src/main/java/balancetalk/game/application/GameService.java, src/main/java/balancetalk/game/application/TempGameService.java, src/main/java/balancetalk/game/dto/TempGameSetDto.java
각 game을 List에 저장하도록 반복하고, 해당 List를 gameSet에 추가하는 방식으로 오류를 해결했습니다.
closes #684
=> 밸런스게임 생성(or 수정 or 임시 저장) API 요청 시 GAME_OPTION 테이블의 GAME_ID가 null로 저장되는 이슈 해결

src/main/java/balancetalk/talkpick/domain/TempTalkPick.java, src/main/java/balancetalk/talkpick/dto/BaseTalkPickFields.java, src/main/java/balancetalk/talkpick/dto/BaseTempTalkPickFields.java, src/main/java/balancetalk/talkpick/dto/TempTalkPickDto.java
원래 `BaseTalkPickFields`에는 모든 필드에 `@NotBlank` 어노테이션이 적용되어 있었습니다. 하지만 `TempTalkPickDto`의 경우 모든 필드에 대해 이러한 검증이 필요하지 않았습니다.
이에 따라 `BaseTempTalkPickFields`를 새로 만들어 상속 구조를 도입했습니다. 이를 통해 `TempTalkPickDto`에서는 필요한 검증만 적용할 수 있게 되었고, 기존 `BaseTalkPickFields`도 유지할 수 있게 되었습니다.
closes #694
=> 톡픽 임시 저장 시 모든 필드에 대한 공백 허용

src/main/java/balancetalk/file/domain/File.java, src/main/java/balancetalk/file/domain/FileHandler.java, src/main/java/balancetalk/file/domain/FileProcessor.java
이미지 업로드 이름에 공백이 들어가면 인코딩이 안되는 문제가 발생합니다. 
이미지 파일의 uploadName의 공백을 제거한 후 인코딩하는 방식을 생각해봤지만, 코드 복잡도 증가로 인해 다시 문자열 조합으로 변경했습니다.
closes #744
=> imgUrl 생성 방식을 URI 대신 문자열 조합으로 변경

src/main/java/balancetalk/game/application/GameService.java, src/main/java/balancetalk/game/dto/GameDto.java, src/main/java/balancetalk/game/presentation/GameController.java
랜덤 밸런스 게임 API 비즈니스 로직은 이렇습니다.
1. 랜덤으로 게임 ID 가져옴
2. 그 값을 기반으로 밸런스 게임 상세조회 API 실행 
따라서, 기존의 상세 조회 비즈니스 로직을 `private` 메서드로 분리하고 랜덤 밸런스 게임 조회, 상세 조회 두가지 API에서 공통으로 사용되게 끔 리팩토링 했습니다.
비회원일 때는 문제가 없었지만 회원일 때 `NPE` 문제가 발생했습니다.
이를 해결하기 위해 서비스 로직에선 랜덤 ID값만 가져오고, 컨트롤러에선 상세 조회 API를 실행함으로써 문제를 해결했습니다. 
closes #890
=> 밸런스 게임 조회 시 NPE 문제 해결 
